import type { ContentItem } from '@/types/content';

// Original, short practice prompts. They deliberately use no copied textbook
// dialogue so they can be bundled with the open-source app.
export const builtinCommunityScenarios: Omit<ContentItem, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Self introduction: who you are',
    text: 'Hi, I am Mei. I work in product design, and I enjoy hiking on weekends.',
    type: 'sentence',
    tags: ['scenario', 'self-introduction', 'speaking'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Self introduction: a follow-up question',
    text: 'It is nice to meet you. What kind of work do you do?',
    type: 'sentence',
    tags: ['scenario', 'self-introduction', 'speaking'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Asking for directions',
    text: 'Excuse me, could you tell me how to get to the nearest subway station?',
    type: 'sentence',
    tags: ['scenario', 'travel', 'directions'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Checking in at a hotel',
    text: 'Hello, I have a reservation under the name Chen for two nights.',
    type: 'sentence',
    tags: ['scenario', 'travel', 'hotel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Starting a meeting',
    text: 'Thanks for joining. Let us review the goal and decide on the next step.',
    type: 'sentence',
    tags: ['scenario', 'work', 'meeting'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Making a polite request',
    text: 'Would you mind sending me the file when you have a moment?',
    type: 'sentence',
    tags: ['scenario', 'work', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Self introduction: first meeting',
    text: 'Hello, I am Lin. I recently moved here to work in marketing. I enjoy trying new food and exploring the city. What do you like to do after work?',
    type: 'article',
    tags: ['scenario', 'self-introduction', 'conversation'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Job interview: tell me about yourself',
    text: 'Thank you for meeting with me. I have three years of experience in customer support. In my last role, I helped improve our response time by organising common questions. I am excited to bring that practical experience to this team.',
    type: 'article',
    tags: ['scenario', 'job-interview', 'work'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Airport: checking in',
    text: 'Good morning. I would like to check in for my flight to Singapore. Here is my passport. May I have an aisle seat if one is available? Do I need to check this bag?',
    type: 'article',
    tags: ['scenario', 'travel', 'airport'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Airport: boarding announcement',
    text: 'Passengers for flight 218, boarding will begin at gate 12 in ten minutes. Please have your passport and boarding pass ready. Families with young children may board first.',
    type: 'article',
    tags: ['scenario', 'travel', 'airport', 'listening'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Hotel: solving a room problem',
    text: 'Hi, I checked into room 405 this afternoon. The air conditioner does not seem to be working. Could someone take a look, or could I move to another room?',
    type: 'article',
    tags: ['scenario', 'travel', 'hotel', 'problem-solving'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Restaurant: ordering and allergies',
    text: 'Could I have the grilled fish, please? I have a nut allergy, so could you tell me whether the sauce contains any nuts? Water is fine for me, thank you.',
    type: 'article',
    tags: ['scenario', 'restaurant', 'food', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Travel: asking for local advice',
    text: 'I have one free afternoon in the city. Is there a neighbourhood you would recommend for a walk and a simple local meal? I prefer somewhere I can reach by public transport.',
    type: 'article',
    tags: ['scenario', 'travel', 'directions', 'conversation'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Work: introducing a project',
    text: 'Today I will give a short update on the project. We finished the first design review last week, and the next step is user testing. I would appreciate your feedback on the schedule before Friday.',
    type: 'article',
    tags: ['scenario', 'workplace', 'meeting', 'presentation'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Doctor: explaining symptoms',
    text: 'I have had a sore throat and a mild fever since yesterday evening. I do not have any allergies that I know of. Could you tell me whether I should rest at home or take any medicine?',
    type: 'article',
    tags: ['scenario', 'medical', 'doctor', 'health'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Shopping: returning an item',
    text: 'Hello, I bought this jacket two days ago, but the size is not right. I still have the receipt and the tags are attached. Could I exchange it for a larger size?',
    type: 'article',
    tags: ['scenario', 'shopping', 'complaint', 'customer-service'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Phone call: rescheduling an appointment',
    text: 'Hi, this is Alex Chen. I have an appointment at three o’clock tomorrow, but I have a conflict at work. Would it be possible to move it to Thursday afternoon instead?',
    type: 'article',
    tags: ['scenario', 'phone', 'appointment', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Customer service: reporting a delivery problem',
    text: 'I am calling about order 4281. The package arrived today, but one item is missing and the box was damaged. Could you check the order and let me know how you can resolve this?',
    type: 'article',
    tags: ['scenario', 'customer-service', 'complaint', 'problem-solving'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Team meeting: disagreeing constructively',
    text: 'I understand the goal of reducing costs, but I am concerned that this option may create more support work later. Could we compare the long-term maintenance cost before we make a final decision?',
    type: 'article',
    tags: ['scenario', 'workplace', 'meeting', 'negotiation'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Negotiation: discussing a project timeline',
    text: 'The proposed deadline is ambitious given the research still required. If we prioritise the core release now, we can deliver a reliable version in six weeks and schedule the remaining features for the following cycle.',
    type: 'article',
    tags: ['scenario', 'workplace', 'negotiation', 'project-management'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Presentation: handling a difficult question',
    text: 'That is an important question. The current data does not let us draw a firm conclusion yet, so I do not want to overstate the result. We are collecting a larger sample and will share an update next month.',
    type: 'article',
    tags: ['scenario', 'workplace', 'presentation', 'question-answer'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Hotel: making a formal complaint',
    text: 'I appreciate your help so far, but the noise continued well after midnight and affected my sleep. I would like to discuss a reasonable solution, such as a room change or an adjustment to the bill.',
    type: 'article',
    tags: ['scenario', 'hotel', 'travel', 'complaint', 'negotiation'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Airport: reporting lost luggage',
    text: 'Excuse me, my suitcase did not arrive on the baggage belt. It is a small black case with a blue tag. Here is my baggage receipt. Could you tell me what I should do next?',
    type: 'article',
    tags: ['scenario', 'travel', 'airport', 'lost-luggage'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
  {
    title: 'Border control: explaining a visit',
    text: 'Good afternoon. I am visiting for a conference and will stay for five days. I am staying at the River Hotel, and I have a return flight on Friday. Here is the confirmation if you need it.',
    type: 'article',
    tags: ['scenario', 'travel', 'airport', 'immigration'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Car rental: collecting a vehicle',
    text: 'Hi, I have a reservation for a compact car under the name Wang. Before I sign, could you explain what insurance is included and whether returning the car with a full tank is required?',
    type: 'article',
    tags: ['scenario', 'travel', 'car-rental', 'customer-service'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Networking: starting a professional conversation',
    text: 'Hi, I do not think we have met. I am Sam, and I work on mobile products. I enjoyed your question during the session. What kind of projects is your team working on at the moment?',
    type: 'article',
    tags: ['scenario', 'networking', 'self-introduction', 'workplace'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'everyday-scenarios',
  },
  {
    title: 'Work: discussing a performance review',
    text: 'I appreciate the feedback. I am proud that I improved our onboarding process, and I would like to strengthen my presentation skills next quarter. Could we agree on one measurable goal and a time to review it?',
    type: 'article',
    tags: ['scenario', 'workplace', 'performance-review', 'goal-setting'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Work: negotiating a compensation offer',
    text: 'Thank you for the offer. I am enthusiastic about the role and the team. Based on the scope of responsibility and my experience leading similar projects, could we discuss whether there is flexibility in the base salary or the professional development budget?',
    type: 'article',
    tags: ['scenario', 'job-interview', 'workplace', 'negotiation', 'salary'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Seminar: asking a focused question',
    text: 'Thank you for the presentation. You mentioned that the sample was limited to one region. How might the findings change if the study included participants from different age groups or locations?',
    type: 'article',
    tags: ['scenario', 'presentation', 'academic', 'question-answer'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'everyday-scenarios',
  },
  {
    title: 'Social plans: declining an invitation politely',
    text: 'Thank you for inviting me. I would really like to join, but I already have an appointment that evening. Could we meet for coffee another day? I am free after work on Wednesday or Thursday.',
    type: 'article',
    tags: ['scenario', 'social', 'invitation', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'everyday-scenarios',
  },
] as const;
