import type { ContentItem } from '@/types/content';

export const builtinPhrases: Omit<ContentItem, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Good morning',
    text: 'Good morning',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How are you',
    text: 'How are you doing today',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Nice to meet you',
    text: 'Nice to meet you',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Thank you very much',
    text: 'Thank you very much',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'See you later',
    text: 'See you later',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Excuse me',
    text: 'Excuse me, could I ask you something?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Could you please help me',
    text: 'Could you please help me with this?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I would like to order',
    text: 'I would like to order a coffee, please',
    type: 'phrase',
    tags: ['daily', 'food'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What do you think',
    text: 'What do you think about this idea?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How about we go',
    text: 'How about we go for a walk?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Let me know',
    text: 'Let me know if you need anything',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'It was nice talking to you',
    text: 'It was nice talking to you today',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I am looking forward to it',
    text: 'I am looking forward to seeing you',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Take your time',
    text: 'Take your time, there is no rush',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'No worries at all',
    text: 'No worries at all, it happens',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Can I have the check',
    text: 'Can I have the check, please?',
    type: 'phrase',
    tags: ['daily', 'food'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Where is the nearest station',
    text: 'Where is the nearest train station?',
    type: 'phrase',
    tags: ['travel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I am sorry for the trouble',
    text: 'I am sorry for the trouble I caused',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Could you repeat that',
    text: 'Could you repeat that, please?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Have a great day',
    text: 'Have a great day ahead!',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What time does it start',
    text: 'What time does the meeting start?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I will be right back',
    text: 'I will be right back in a moment',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'That sounds like a great idea',
    text: 'That sounds like a great idea to me',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Do you mind if I sit here',
    text: 'Do you mind if I sit here?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I really appreciate your help',
    text: 'I really appreciate your help with this',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Break a leg',
    text: 'Break a leg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Piece of cake',
    text: 'It is a piece of cake',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Hit the nail on the head',
    text: 'You hit the nail on the head',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Under the weather',
    text: 'I am feeling under the weather',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Burn the midnight oil',
    text: 'She had to burn the midnight oil to finish the project',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Get the ball rolling',
    text: 'Let us get the ball rolling on this project',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Think outside the box',
    text: 'We need to think outside the box to solve this',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'On the same page',
    text: 'Let us make sure we are on the same page',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Touch base',
    text: 'I will touch base with you next week',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'A blessing in disguise',
    text: 'Losing that job turned out to be a blessing in disguise',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Better late than never',
    text: 'Better late than never, I always say',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Cost an arm and a leg',
    text: 'That new car cost an arm and a leg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Let the cat out of the bag',
    text: 'She accidentally let the cat out of the bag about the surprise party',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Once in a blue moon',
    text: 'We only see each other once in a blue moon',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Speak of the devil',
    text: 'Speak of the devil, here she comes now',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'The ball is in your court',
    text: 'The ball is in your court',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The elephant in the room',
    text: 'Nobody wants to talk about the elephant in the room',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'A double-edged sword',
    text: 'Social media is a double-edged sword for modern society',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Par for the course',
    text: 'Delays are par for the course in this industry',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The tip of the iceberg',
    text: 'What we have seen so far is just the tip of the iceberg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Burning bridges',
    text: 'Be careful not to burn your bridges when leaving a job',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Reading between the lines',
    text: 'You have to read between the lines to understand the real message',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Bite the bullet',
    text: 'Sometimes you just have to bite the bullet and face the challenge',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Cut to the chase',
    text: 'Let me cut to the chase and tell you what happened',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Devil is in the details',
    text: 'The devil is in the details, so review everything carefully',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Go the extra mile',
    text: 'She always goes the extra mile for her clients',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Leave no stone unturned',
    text: 'The detective left no stone unturned in the investigation',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The whole nine yards',
    text: 'They decorated the house with lights, ornaments, the whole nine yards',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'When pigs fly',
    text: 'He said he would clean his room when pigs fly',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'A penny for your thoughts',
    text: 'You look deep in thought, a penny for your thoughts?',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
];
