import type { ContentItem } from '@/types/content';

export const builtinPhrases: Omit<ContentItem, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Good morning',
    text: 'Good morning',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How are you',
    text: 'How are you doing today',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Nice to meet you',
    text: 'Nice to meet you',
    type: 'phrase',
    tags: ['greeting'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Thank you very much',
    text: 'Thank you very much',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'See you later',
    text: 'See you later',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Excuse me',
    text: 'Excuse me, could I ask you something?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Could you please help me',
    text: 'Could you please help me with this?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I would like to order',
    text: 'I would like to order a coffee, please',
    type: 'phrase',
    tags: ['daily', 'food'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What do you think',
    text: 'What do you think about this idea?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How about we go',
    text: 'How about we go for a walk?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Let me know',
    text: 'Let me know if you need anything',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'It was nice talking to you',
    text: 'It was nice talking to you today',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I am looking forward to it',
    text: 'I am looking forward to seeing you',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Take your time',
    text: 'Take your time, there is no rush',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'No worries at all',
    text: 'No worries at all, it happens',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Can I have the check',
    text: 'Can I have the check, please?',
    type: 'phrase',
    tags: ['daily', 'food'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Where is the nearest station',
    text: 'Where is the nearest train station?',
    type: 'phrase',
    tags: ['travel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I am sorry for the trouble',
    text: 'I am sorry for the trouble I caused',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Could you repeat that',
    text: 'Could you repeat that, please?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Have a great day',
    text: 'Have a great day ahead!',
    type: 'phrase',
    tags: ['farewell'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What time does it start',
    text: 'What time does the meeting start?',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I will be right back',
    text: 'I will be right back in a moment',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'That sounds like a great idea',
    text: 'That sounds like a great idea to me',
    type: 'phrase',
    tags: ['daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Do you mind if I sit here',
    text: 'Do you mind if I sit here?',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I really appreciate your help',
    text: 'I really appreciate your help with this',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Break a leg',
    text: 'Break a leg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Piece of cake',
    text: 'It is a piece of cake',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Hit the nail on the head',
    text: 'You hit the nail on the head',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Under the weather',
    text: 'I am feeling under the weather',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Burn the midnight oil',
    text: 'She had to burn the midnight oil to finish the project',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Get the ball rolling',
    text: 'Let us get the ball rolling on this project',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Think outside the box',
    text: 'We need to think outside the box to solve this',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'On the same page',
    text: 'Let us make sure we are on the same page',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Touch base',
    text: 'I will touch base with you next week',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'A blessing in disguise',
    text: 'Losing that job turned out to be a blessing in disguise',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Better late than never',
    text: 'Better late than never, I always say',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Cost an arm and a leg',
    text: 'That new car cost an arm and a leg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Let the cat out of the bag',
    text: 'She accidentally let the cat out of the bag about the surprise party',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Once in a blue moon',
    text: 'We only see each other once in a blue moon',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Speak of the devil',
    text: 'Speak of the devil, here she comes now',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'The ball is in your court',
    text: 'The ball is in your court',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The elephant in the room',
    text: 'Nobody wants to talk about the elephant in the room',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'A double-edged sword',
    text: 'Social media is a double-edged sword for modern society',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Par for the course',
    text: 'Delays are par for the course in this industry',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The tip of the iceberg',
    text: 'What we have seen so far is just the tip of the iceberg',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Burning bridges',
    text: 'Be careful not to burn your bridges when leaving a job',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Reading between the lines',
    text: 'You have to read between the lines to understand the real message',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Bite the bullet',
    text: 'Sometimes you just have to bite the bullet and face the challenge',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Cut to the chase',
    text: 'Let me cut to the chase and tell you what happened',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Devil is in the details',
    text: 'The devil is in the details, so review everything carefully',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Go the extra mile',
    text: 'She always goes the extra mile for her clients',
    type: 'phrase',
    tags: ['idiom', 'business'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Leave no stone unturned',
    text: 'The detective left no stone unturned in the investigation',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'The whole nine yards',
    text: 'They decorated the house with lights, ornaments, the whole nine yards',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'When pigs fly',
    text: 'He said he would clean his room when pigs fly',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'A penny for your thoughts',
    text: 'You look deep in thought, a penny for your thoughts?',
    type: 'phrase',
    tags: ['idiom'],
    source: 'builtin',
    difficulty: 'advanced',
    category: 'idiom',
  },

  // ── Email Phrases ─────────────────────────────────────────────
  {
    title: 'I hope this email finds you well',
    text: 'I hope this email finds you well',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'Looking forward to hearing from you',
    text: 'Looking forward to hearing from you',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'Please find the document attached',
    text: 'Please find the document attached for your review',
    type: 'phrase',
    tags: ['email', 'business'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'I hope you had a great weekend',
    text: 'I hope you had a great weekend',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'Thank you for getting back to me',
    text: 'Thank you for getting back to me so quickly',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },
  {
    title: 'I wanted to follow up on this',
    text: 'I wanted to follow up on our previous conversation',
    type: 'phrase',
    tags: ['email', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },
  {
    title: 'Please do not hesitate to reach out',
    text: 'Please do not hesitate to reach out if you have any questions',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },
  {
    title: 'I am writing to inform you',
    text: 'I am writing to inform you about an important update',
    type: 'phrase',
    tags: ['email', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },
  {
    title: 'I would appreciate your prompt response',
    text: 'I would appreciate your prompt response on this matter',
    type: 'phrase',
    tags: ['email', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },
  {
    title: 'I have copied my colleague on this email',
    text: 'I have copied my colleague on this email for reference',
    type: 'phrase',
    tags: ['email', 'business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'email',
  },

  // ── Daily Conversation ────────────────────────────────────────
  {
    title: 'How is it going',
    text: 'Hey, how is it going?',
    type: 'phrase',
    tags: ['greeting', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What have you been up to lately',
    text: 'What have you been up to lately?',
    type: 'phrase',
    tags: ['daily', 'social'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Long time no see',
    text: 'Long time no see! How have you been?',
    type: 'phrase',
    tags: ['greeting', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What do you do for a living',
    text: 'What do you do for a living?',
    type: 'phrase',
    tags: ['daily', 'social'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I will get back to you on that',
    text: 'I will get back to you on that later',
    type: 'phrase',
    tags: ['daily', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How was your weekend',
    text: 'How was your weekend? Did you do anything fun?',
    type: 'phrase',
    tags: ['daily', 'social'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },

  // ── Business / Professional ───────────────────────────────────
  {
    title: 'Let us get started',
    text: "Let us get started with today's agenda",
    type: 'phrase',
    tags: ['business'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'business',
  },
  {
    title: 'Could you elaborate on that',
    text: 'Could you elaborate on that point?',
    type: 'phrase',
    tags: ['business', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'I completely agree',
    text: 'I completely agree with your suggestion',
    type: 'phrase',
    tags: ['business', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'business',
  },
  {
    title: 'I am afraid I have to disagree',
    text: 'I am afraid I have to disagree on this point',
    type: 'phrase',
    tags: ['business', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Let me summarize the main points',
    text: 'Let me quickly summarize the main points we discussed',
    type: 'phrase',
    tags: ['business'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Thank you all for your time',
    text: 'Thank you all for your time today',
    type: 'phrase',
    tags: ['business', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'business',
  },

  // ── Social / Polite Expressions ───────────────────────────────
  {
    title: 'Do not mention it',
    text: 'Do not mention it, happy to help',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I apologize for the inconvenience',
    text: 'I apologize for the inconvenience caused',
    type: 'phrase',
    tags: ['polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'polite',
  },
  {
    title: 'Could you do me a favor',
    text: 'Could you do me a favor?',
    type: 'phrase',
    tags: ['polite', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I could not agree more',
    text: 'I could not agree more with that',
    type: 'phrase',
    tags: ['polite', 'daily'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'polite',
  },
  {
    title: 'In my opinion',
    text: 'In my opinion, that would be a better choice',
    type: 'phrase',
    tags: ['daily', 'social'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Let us grab a coffee sometime',
    text: 'Let us grab a coffee sometime and catch up',
    type: 'phrase',
    tags: ['daily', 'social'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'I see your point',
    text: 'I see your point, but I think differently',
    type: 'phrase',
    tags: ['daily', 'polite'],
    source: 'builtin',
    difficulty: 'intermediate',
    category: 'daily',
  },

  // ── Travel / Shopping ─────────────────────────────────────────
  {
    title: 'How much does this cost',
    text: 'How much does this cost?',
    type: 'phrase',
    tags: ['travel', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I am just looking thanks',
    text: 'I am just looking, thanks',
    type: 'phrase',
    tags: ['travel', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'Can I pay by card',
    text: 'Can I pay by card?',
    type: 'phrase',
    tags: ['travel', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I would like to check in please',
    text: 'I would like to check in, please',
    type: 'phrase',
    tags: ['travel', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I have a reservation',
    text: 'I have a reservation under the name Johnson',
    type: 'phrase',
    tags: ['travel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'Excuse me how do I get to',
    text: 'Excuse me, how do I get to the train station?',
    type: 'phrase',
    tags: ['travel', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'Is it within walking distance',
    text: 'Is it within walking distance from here?',
    type: 'phrase',
    tags: ['travel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'Do you have this in a different size',
    text: 'Do you have this in a different size?',
    type: 'phrase',
    tags: ['travel', 'daily'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'What time is check-out',
    text: 'What time is check-out?',
    type: 'phrase',
    tags: ['travel'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I would like to order please',
    text: 'I would like to order the grilled chicken, please',
    type: 'phrase',
    tags: ['travel', 'food', 'polite'],
    source: 'builtin',
    difficulty: 'beginner',
    category: 'travel',
  },
];
