import type { ContentItem } from '@/types/content';

export const builtinWords: Omit<ContentItem, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // === BEGINNER (40 words) ===
  { title: 'hello', text: 'hello', type: 'word', tags: ['greeting', 'noun'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'world', text: 'world', type: 'word', tags: ['basic', 'noun'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'computer', text: 'computer', type: 'word', tags: ['technology', 'noun'], source: 'builtin', difficulty: 'beginner', category: 'technology' },
  { title: 'language', text: 'language', type: 'word', tags: ['education', 'noun'], source: 'builtin', difficulty: 'beginner', category: 'education' },
  { title: 'practice', text: 'practice', type: 'word', tags: ['education', 'verb'], source: 'builtin', difficulty: 'beginner', category: 'education' },
  { title: 'beautiful', text: 'beautiful', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'important', text: 'important', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'understand', text: 'understand', type: 'word', tags: ['verb'], source: 'builtin', difficulty: 'beginner', category: 'education' },
  { title: 'appreciate', text: 'appreciate', type: 'word', tags: ['verb', 'emotions'], source: 'builtin', difficulty: 'beginner', category: 'emotions' },
  { title: 'schedule', text: 'schedule', type: 'word', tags: ['noun', 'verb'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'comfortable', text: 'comfortable', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'delicious', text: 'delicious', type: 'word', tags: ['adjective', 'food'], source: 'builtin', difficulty: 'beginner', category: 'food' },
  { title: 'journey', text: 'journey', type: 'word', tags: ['noun', 'travel'], source: 'builtin', difficulty: 'beginner', category: 'travel' },
  { title: 'adventure', text: 'adventure', type: 'word', tags: ['noun', 'travel'], source: 'builtin', difficulty: 'beginner', category: 'travel' },
  { title: 'curious', text: 'curious', type: 'word', tags: ['adjective', 'emotions'], source: 'builtin', difficulty: 'beginner', category: 'emotions' },
  { title: 'generous', text: 'generous', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'emotions' },
  { title: 'breakfast', text: 'breakfast', type: 'word', tags: ['noun', 'food'], source: 'builtin', difficulty: 'beginner', category: 'food' },
  { title: 'weather', text: 'weather', type: 'word', tags: ['noun', 'nature'], source: 'builtin', difficulty: 'beginner', category: 'nature' },
  { title: 'family', text: 'family', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'friend', text: 'friend', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'remember', text: 'remember', type: 'word', tags: ['verb'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'different', text: 'different', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'together', text: 'together', type: 'word', tags: ['adverb'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'favorite', text: 'favorite', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'exercise', text: 'exercise', type: 'word', tags: ['noun', 'verb', 'body'], source: 'builtin', difficulty: 'beginner', category: 'body' },
  { title: 'healthy', text: 'healthy', type: 'word', tags: ['adjective', 'body'], source: 'builtin', difficulty: 'beginner', category: 'body' },
  { title: 'kitchen', text: 'kitchen', type: 'word', tags: ['noun', 'food'], source: 'builtin', difficulty: 'beginner', category: 'food' },
  { title: 'garden', text: 'garden', type: 'word', tags: ['noun', 'nature'], source: 'builtin', difficulty: 'beginner', category: 'nature' },
  { title: 'mountain', text: 'mountain', type: 'word', tags: ['noun', 'nature'], source: 'builtin', difficulty: 'beginner', category: 'nature' },
  { title: 'ocean', text: 'ocean', type: 'word', tags: ['noun', 'nature'], source: 'builtin', difficulty: 'beginner', category: 'nature' },
  { title: 'library', text: 'library', type: 'word', tags: ['noun', 'education'], source: 'builtin', difficulty: 'beginner', category: 'education' },
  { title: 'hospital', text: 'hospital', type: 'word', tags: ['noun', 'body'], source: 'builtin', difficulty: 'beginner', category: 'body' },
  { title: 'restaurant', text: 'restaurant', type: 'word', tags: ['noun', 'food'], source: 'builtin', difficulty: 'beginner', category: 'food' },
  { title: 'vacation', text: 'vacation', type: 'word', tags: ['noun', 'travel'], source: 'builtin', difficulty: 'beginner', category: 'travel' },
  { title: 'surprise', text: 'surprise', type: 'word', tags: ['noun', 'verb', 'emotions'], source: 'builtin', difficulty: 'beginner', category: 'emotions' },
  { title: 'celebrate', text: 'celebrate', type: 'word', tags: ['verb'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'discover', text: 'discover', type: 'word', tags: ['verb'], source: 'builtin', difficulty: 'beginner', category: 'education' },
  { title: 'imagine', text: 'imagine', type: 'word', tags: ['verb', 'emotions'], source: 'builtin', difficulty: 'beginner', category: 'emotions' },
  { title: 'neighbor', text: 'neighbor', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'beginner', category: 'daily-life' },
  { title: 'shoulder', text: 'shoulder', type: 'word', tags: ['noun', 'body'], source: 'builtin', difficulty: 'beginner', category: 'body' },

  // === INTERMEDIATE (35 words) ===
  { title: 'experience', text: 'experience', type: 'word', tags: ['noun', 'education'], source: 'builtin', difficulty: 'intermediate', category: 'education' },
  { title: 'knowledge', text: 'knowledge', type: 'word', tags: ['noun', 'education'], source: 'builtin', difficulty: 'intermediate', category: 'education' },
  { title: 'environment', text: 'environment', type: 'word', tags: ['noun', 'nature'], source: 'builtin', difficulty: 'intermediate', category: 'nature' },
  { title: 'technology', text: 'technology', type: 'word', tags: ['noun', 'technology'], source: 'builtin', difficulty: 'intermediate', category: 'technology' },
  { title: 'communication', text: 'communication', type: 'word', tags: ['noun', 'social'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'opportunity', text: 'opportunity', type: 'word', tags: ['noun', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'development', text: 'development', type: 'word', tags: ['noun', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'analyze', text: 'analyze', type: 'word', tags: ['verb', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'significant', text: 'significant', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'hypothesis', text: 'hypothesis', type: 'word', tags: ['noun', 'science'], source: 'builtin', difficulty: 'intermediate', category: 'science' },
  { title: 'negotiate', text: 'negotiate', type: 'word', tags: ['verb', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'collaborate', text: 'collaborate', type: 'word', tags: ['verb', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'implement', text: 'implement', type: 'word', tags: ['verb', 'technology'], source: 'builtin', difficulty: 'intermediate', category: 'technology' },
  { title: 'evaluate', text: 'evaluate', type: 'word', tags: ['verb', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'perspective', text: 'perspective', type: 'word', tags: ['noun', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'consequence', text: 'consequence', type: 'word', tags: ['noun', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'demonstrate', text: 'demonstrate', type: 'word', tags: ['verb', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'contribute', text: 'contribute', type: 'word', tags: ['verb'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'establish', text: 'establish', type: 'word', tags: ['verb', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'investigate', text: 'investigate', type: 'word', tags: ['verb', 'science'], source: 'builtin', difficulty: 'intermediate', category: 'science' },
  { title: 'phenomenon', text: 'phenomenon', type: 'word', tags: ['noun', 'science'], source: 'builtin', difficulty: 'intermediate', category: 'science' },
  { title: 'strategy', text: 'strategy', type: 'word', tags: ['noun', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'influence', text: 'influence', type: 'word', tags: ['noun', 'verb'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'guarantee', text: 'guarantee', type: 'word', tags: ['noun', 'verb', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'sufficient', text: 'sufficient', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'inevitable', text: 'inevitable', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'controversy', text: 'controversy', type: 'word', tags: ['noun', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'infrastructure', text: 'infrastructure', type: 'word', tags: ['noun', 'technology'], source: 'builtin', difficulty: 'intermediate', category: 'technology' },
  { title: 'sustainable', text: 'sustainable', type: 'word', tags: ['adjective', 'nature'], source: 'builtin', difficulty: 'intermediate', category: 'nature' },
  { title: 'curriculum', text: 'curriculum', type: 'word', tags: ['noun', 'education'], source: 'builtin', difficulty: 'intermediate', category: 'education' },
  { title: 'preliminary', text: 'preliminary', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'comprehensive', text: 'comprehensive', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'contemporary', text: 'contemporary', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'intermediate', category: 'academic' },
  { title: 'acquisition', text: 'acquisition', type: 'word', tags: ['noun', 'business'], source: 'builtin', difficulty: 'intermediate', category: 'business' },
  { title: 'methodology', text: 'methodology', type: 'word', tags: ['noun', 'science'], source: 'builtin', difficulty: 'intermediate', category: 'science' },

  // === ADVANCED (25 words) ===
  { title: 'responsibility', text: 'responsibility', type: 'word', tags: ['noun', 'character'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'extraordinary', text: 'extraordinary', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'sophisticated', text: 'sophisticated', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'accomplishment', text: 'accomplishment', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'determination', text: 'determination', type: 'word', tags: ['noun', 'character'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'ubiquitous', text: 'ubiquitous', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'paradigm', text: 'paradigm', type: 'word', tags: ['noun', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'juxtaposition', text: 'juxtaposition', type: 'word', tags: ['noun', 'literature'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'ephemeral', text: 'ephemeral', type: 'word', tags: ['adjective', 'literature'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'pragmatic', text: 'pragmatic', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'meticulous', text: 'meticulous', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'eloquent', text: 'eloquent', type: 'word', tags: ['adjective', 'literature'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'ambiguous', text: 'ambiguous', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'benevolent', text: 'benevolent', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'quintessential', text: 'quintessential', type: 'word', tags: ['adjective', 'literature'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'serendipity', text: 'serendipity', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'resilience', text: 'resilience', type: 'word', tags: ['noun', 'character'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'dichotomy', text: 'dichotomy', type: 'word', tags: ['noun', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'idiosyncratic', text: 'idiosyncratic', type: 'word', tags: ['adjective', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'magnanimous', text: 'magnanimous', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'surreptitious', text: 'surreptitious', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'perspicacious', text: 'perspicacious', type: 'word', tags: ['adjective', 'literature'], source: 'builtin', difficulty: 'advanced', category: 'literature' },
  { title: 'recalcitrant', text: 'recalcitrant', type: 'word', tags: ['adjective'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
  { title: 'ameliorate', text: 'ameliorate', type: 'word', tags: ['verb', 'academic'], source: 'builtin', difficulty: 'advanced', category: 'academic' },
  { title: 'conundrum', text: 'conundrum', type: 'word', tags: ['noun'], source: 'builtin', difficulty: 'advanced', category: 'formal' },
];
