import { wordSimilarity } from './levenshtein';
import { normalizeSpeechWords } from './speech-feedback';

export interface PronunciationSound {
  id: string;
  group: 'vowels' | 'consonants' | 'long-vowels';
  ipa: string;
  soundText: string;
  pattern?: string;
  exampleWord: string;
  examples: string[];
  tip: string;
}

export interface PronunciationAttemptScore {
  score: number;
  passed: boolean;
  label: 'Clear' | 'Close' | 'Try again' | 'No speech';
  recognized: string;
}

const SOUND_ALIASES: Record<string, string[]> = {
  ah: ['a'],
  aah: ['a'],
  uh: ['a', 'the'],
  eh: ['e'],
  ay: ['a', 'hey'],
  er: ['her'],
  ih: ['i'],
  ee: ['e'],
  eye: ['i'],
  oh: ['o'],
  ow: ['out'],
  oy: ['boy'],
  oo: ['u'],
  uuh: ['book'],
  buh: ['b', 'bee'],
  puh: ['p', 'pea'],
  ch: ['chair'],
  duh: ['d', 'day'],
  tuh: ['t', 'tea'],
  fff: ['f'],
  vvv: ['v'],
  guh: ['g', 'go'],
  kuh: ['k'],
  huh: ['h'],
  j: ['job'],
  mmm: ['m'],
  nnn: ['n'],
  ng: ['sing'],
  lll: ['l'],
  rrr: ['r'],
  sss: ['s'],
  zzz: ['z'],
  sh: ['she'],
  zh: ['vision'],
  th: ['think', 'this'],
  wuh: ['w', 'we'],
  yuh: ['y', 'yes'],
};

export const PRONUNCIATION_SOUNDS: PronunciationSound[] = [
  {
    id: 'aa',
    group: 'vowels',
    ipa: 'ɑ',
    soundText: 'ah',
    exampleWord: 'hot',
    examples: ['hot', 'not', 'father'],
    tip: 'Open your mouth and keep the sound low and relaxed.',
  },
  {
    id: 'ae',
    group: 'vowels',
    ipa: 'æ',
    soundText: 'aah',
    exampleWord: 'cat',
    examples: ['cat', 'map', 'bag'],
    tip: 'Open wide and keep the vowel short.',
  },
  {
    id: 'uh',
    group: 'vowels',
    ipa: 'ʌ',
    soundText: 'uh',
    exampleWord: 'but',
    examples: ['but', 'cup', 'sun'],
    tip: 'Use a short central sound.',
  },
  {
    id: 'eh',
    group: 'vowels',
    ipa: 'ɛ',
    soundText: 'eh',
    exampleWord: 'bed',
    examples: ['bed', 'red', 'check'],
    tip: 'Keep the sound short and relaxed.',
  },
  {
    id: 'ei',
    group: 'vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    exampleWord: 'say',
    examples: ['say', 'rain', 'cake', 'play', 'eight'],
    tip: 'Start with /e/ and glide toward /ɪ/.',
  },
  {
    id: 'er',
    group: 'vowels',
    ipa: 'ɚ',
    soundText: 'er',
    exampleWord: 'bird',
    examples: ['bird', 'her', 'word'],
    tip: 'Curl or bunch the tongue slightly for the R-colored vowel.',
  },
  {
    id: 'ih',
    group: 'vowels',
    ipa: 'ɪ',
    soundText: 'ih',
    exampleWord: 'ship',
    examples: ['ship', 'sit', 'busy'],
    tip: 'Keep it short; do not stretch it into /i/.',
  },
  {
    id: 'iy',
    group: 'vowels',
    ipa: 'i',
    soundText: 'ee',
    exampleWord: 'sheep',
    examples: ['sheep', 'see', 'team'],
    tip: 'Smile slightly and hold the vowel.',
  },
  {
    id: 'schwa',
    group: 'vowels',
    ipa: 'ə',
    soundText: 'uh',
    exampleWord: 'about',
    examples: ['about', 'sofa', 'again'],
    tip: 'Use a weak, unstressed central vowel.',
  },
  {
    id: 'ou',
    group: 'vowels',
    ipa: 'oʊ',
    soundText: 'oh',
    exampleWord: 'boat',
    examples: ['boat', 'home', 'snow'],
    tip: 'Round your lips and glide.',
  },
  {
    id: 'uu',
    group: 'vowels',
    ipa: 'ʊ',
    soundText: 'uuh',
    exampleWord: 'foot',
    examples: ['foot', 'book', 'good'],
    tip: 'Short rounded vowel, lighter than /u/.',
  },
  {
    id: 'uw',
    group: 'vowels',
    ipa: 'u',
    soundText: 'oo',
    exampleWord: 'food',
    examples: ['food', 'blue', 'too'],
    tip: 'Round your lips and hold the vowel.',
  },
  {
    id: 'au',
    group: 'vowels',
    ipa: 'aʊ',
    soundText: 'ow',
    exampleWord: 'cow',
    examples: ['cow', 'now', 'out'],
    tip: 'Start open and glide to a rounded ending.',
  },
  {
    id: 'ai',
    group: 'vowels',
    ipa: 'aɪ',
    soundText: 'eye',
    exampleWord: 'time',
    examples: ['time', 'my', 'light'],
    tip: 'Start open and glide upward.',
  },
  {
    id: 'oi',
    group: 'vowels',
    ipa: 'ɔɪ',
    soundText: 'oy',
    exampleWord: 'boy',
    examples: ['boy', 'voice', 'choice'],
    tip: 'Start rounded and glide to /ɪ/.',
  },
  {
    id: 'b',
    group: 'consonants',
    ipa: 'b',
    soundText: 'buh',
    exampleWord: 'book',
    examples: ['book', 'baby', 'cab'],
    tip: 'Close both lips, use voice, then release.',
  },
  {
    id: 'p',
    group: 'consonants',
    ipa: 'p',
    soundText: 'puh',
    exampleWord: 'pen',
    examples: ['pen', 'paper', 'cap'],
    tip: 'Close both lips, no voice, then release a small puff of air.',
  },
  {
    id: 'ch',
    group: 'consonants',
    ipa: 'tʃ',
    soundText: 'ch',
    exampleWord: 'chair',
    examples: ['chair', 'choose', 'watch'],
    tip: 'Stop the air, then release with a sh-like sound.',
  },
  {
    id: 'd',
    group: 'consonants',
    ipa: 'd',
    soundText: 'duh',
    exampleWord: 'day',
    examples: ['day', 'dog', 'red'],
    tip: 'Touch behind the teeth and use voice.',
  },
  {
    id: 't',
    group: 'consonants',
    ipa: 't',
    soundText: 'tuh',
    exampleWord: 'tea',
    examples: ['tea', 'table', 'cat'],
    tip: 'Touch behind the teeth, no voice, then release.',
  },
  {
    id: 'f',
    group: 'consonants',
    ipa: 'f',
    soundText: 'fff',
    exampleWord: 'fish',
    examples: ['fish', 'phone', 'leaf'],
    tip: 'Teeth lightly touch the lower lip; no voice.',
  },
  {
    id: 'v',
    group: 'consonants',
    ipa: 'v',
    soundText: 'vvv',
    exampleWord: 'voice',
    examples: ['voice', 'very', 'love'],
    tip: 'Teeth lightly touch the lower lip; use voice.',
  },
  {
    id: 'g',
    group: 'consonants',
    ipa: 'g',
    soundText: 'guh',
    exampleWord: 'go',
    examples: ['go', 'green', 'bag'],
    tip: 'Back of tongue touches the soft palate; use voice.',
  },
  {
    id: 'k',
    group: 'consonants',
    ipa: 'k',
    soundText: 'kuh',
    exampleWord: 'cat',
    examples: ['cat', 'key', 'back'],
    tip: 'Back of tongue touches the soft palate; no voice.',
  },
  {
    id: 'h',
    group: 'consonants',
    ipa: 'h',
    soundText: 'huh',
    exampleWord: 'hat',
    examples: ['hat', 'home', 'behind'],
    tip: 'Let air pass through the throat without friction.',
  },
  {
    id: 'j',
    group: 'consonants',
    ipa: 'dʒ',
    soundText: 'j',
    exampleWord: 'job',
    examples: ['job', 'juice', 'bridge'],
    tip: 'Voice the CH sound.',
  },
  {
    id: 'm',
    group: 'consonants',
    ipa: 'm',
    soundText: 'mmm',
    exampleWord: 'moon',
    examples: ['moon', 'map', 'team'],
    tip: 'Close both lips and hum through the nose.',
  },
  {
    id: 'n',
    group: 'consonants',
    ipa: 'n',
    soundText: 'nnn',
    exampleWord: 'name',
    examples: ['name', 'new', 'sun'],
    tip: 'Touch behind the teeth and let air pass through the nose.',
  },
  {
    id: 'ng',
    group: 'consonants',
    ipa: 'ŋ',
    soundText: 'ng',
    exampleWord: 'sing',
    examples: ['sing', 'long', 'thinking'],
    tip: 'Back of tongue lifts while air passes through the nose.',
  },
  {
    id: 'l',
    group: 'consonants',
    ipa: 'l',
    soundText: 'lll',
    exampleWord: 'light',
    examples: ['light', 'look', 'feel'],
    tip: 'Touch the tongue behind the upper teeth.',
  },
  {
    id: 'r',
    group: 'consonants',
    ipa: 'r',
    soundText: 'rrr',
    exampleWord: 'rain',
    examples: ['rain', 'road', 'right'],
    tip: 'Pull the tongue back without touching the roof.',
  },
  {
    id: 's',
    group: 'consonants',
    ipa: 's',
    soundText: 'sss',
    exampleWord: 'sun',
    examples: ['sun', 'see', 'bus'],
    tip: 'Narrow the airflow behind the teeth; no voice.',
  },
  {
    id: 'z',
    group: 'consonants',
    ipa: 'z',
    soundText: 'zzz',
    exampleWord: 'zoo',
    examples: ['zoo', 'busy', 'has'],
    tip: 'Same mouth shape as /s/, but use voice.',
  },
  {
    id: 'sh',
    group: 'consonants',
    ipa: 'ʃ',
    soundText: 'sh',
    exampleWord: 'she',
    examples: ['she', 'ship', 'wish'],
    tip: 'Round the lips slightly and push air through a wider channel.',
  },
  {
    id: 'zh',
    group: 'consonants',
    ipa: 'ʒ',
    soundText: 'zh',
    exampleWord: 'vision',
    examples: ['vision', 'measure', 'beige'],
    tip: 'Voice the /ʃ/ sound.',
  },
  {
    id: 'th-voiceless',
    group: 'consonants',
    ipa: 'θ',
    soundText: 'th',
    exampleWord: 'think',
    examples: ['think', 'three', 'path'],
    tip: 'Tongue lightly between teeth; no voice.',
  },
  {
    id: 'th-voiced',
    group: 'consonants',
    ipa: 'ð',
    soundText: 'th',
    exampleWord: 'this',
    examples: ['this', 'they', 'breathe'],
    tip: 'Same tongue position as /θ/, but use voice.',
  },
  {
    id: 'w',
    group: 'consonants',
    ipa: 'w',
    soundText: 'wuh',
    exampleWord: 'we',
    examples: ['we', 'water', 'window'],
    tip: 'Round both lips and glide into the vowel.',
  },
  {
    id: 'y',
    group: 'consonants',
    ipa: 'j',
    soundText: 'yuh',
    exampleWord: 'yes',
    examples: ['yes', 'you', 'yard'],
    tip: 'Start with a high tongue position and glide into the vowel.',
  },
  {
    id: 'long-a-a-e',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'a-e',
    exampleWord: 'cake',
    examples: ['cake', 'name', 'late'],
    tip: 'Long A with silent e: a-e.',
  },
  {
    id: 'long-a-ai',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'ai',
    exampleWord: 'rain',
    examples: ['rain', 'train', 'mail'],
    tip: 'Long A with ai, often in the middle of words.',
  },
  {
    id: 'long-a-ay',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'ay',
    exampleWord: 'play',
    examples: ['play', 'day', 'say'],
    tip: 'Long A with ay, often at the end of words.',
  },
  {
    id: 'long-a-ei',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'ei',
    exampleWord: 'vein',
    examples: ['vein', 'rein', 'veil'],
    tip: 'Long A with ei.',
  },
  {
    id: 'long-a-eigh',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'eigh',
    exampleWord: 'eight',
    examples: ['eight', 'weight', 'neighbor'],
    tip: 'Long A with eigh.',
  },
  {
    id: 'long-a-ey',
    group: 'long-vowels',
    ipa: 'eɪ',
    soundText: 'ay',
    pattern: 'ey',
    exampleWord: 'they',
    examples: ['they', 'grey', 'prey'],
    tip: 'Long A with ey.',
  },
  {
    id: 'long-e-ee',
    group: 'long-vowels',
    ipa: 'i',
    soundText: 'ee',
    pattern: 'ee',
    exampleWord: 'see',
    examples: ['see', 'green', 'sleep'],
    tip: 'Long E with ee.',
  },
  {
    id: 'long-e-ea',
    group: 'long-vowels',
    ipa: 'i',
    soundText: 'ee',
    pattern: 'ea',
    exampleWord: 'team',
    examples: ['team', 'read', 'seat'],
    tip: 'Long E with ea.',
  },
  {
    id: 'long-e-ey',
    group: 'long-vowels',
    ipa: 'i',
    soundText: 'ee',
    pattern: 'ey',
    exampleWord: 'key',
    examples: ['key', 'money', 'honey'],
    tip: 'Long E with ey.',
  },
  {
    id: 'long-e-y',
    group: 'long-vowels',
    ipa: 'i',
    soundText: 'ee',
    pattern: 'final y',
    exampleWord: 'happy',
    examples: ['happy', 'city', 'baby'],
    tip: 'Long E with final y.',
  },
  {
    id: 'long-i-i-e',
    group: 'long-vowels',
    ipa: 'aɪ',
    soundText: 'eye',
    pattern: 'i-e',
    exampleWord: 'time',
    examples: ['time', 'bike', 'smile'],
    tip: 'Long I with silent e: i-e.',
  },
  {
    id: 'long-i-igh',
    group: 'long-vowels',
    ipa: 'aɪ',
    soundText: 'eye',
    pattern: 'igh',
    exampleWord: 'light',
    examples: ['light', 'night', 'right'],
    tip: 'Long I with igh.',
  },
  {
    id: 'long-i-y',
    group: 'long-vowels',
    ipa: 'aɪ',
    soundText: 'eye',
    pattern: 'final y',
    exampleWord: 'my',
    examples: ['my', 'try', 'fly'],
    tip: 'Long I with final y.',
  },
  {
    id: 'long-i-ie',
    group: 'long-vowels',
    ipa: 'aɪ',
    soundText: 'eye',
    pattern: 'ie',
    exampleWord: 'pie',
    examples: ['pie', 'tie', 'lie'],
    tip: 'Long I with ie.',
  },
  {
    id: 'long-o-o-e',
    group: 'long-vowels',
    ipa: 'oʊ',
    soundText: 'oh',
    pattern: 'o-e',
    exampleWord: 'home',
    examples: ['home', 'note', 'rose'],
    tip: 'Long O with silent e: o-e.',
  },
  {
    id: 'long-o-oa',
    group: 'long-vowels',
    ipa: 'oʊ',
    soundText: 'oh',
    pattern: 'oa',
    exampleWord: 'boat',
    examples: ['boat', 'road', 'coat'],
    tip: 'Long O with oa.',
  },
  {
    id: 'long-o-ow',
    group: 'long-vowels',
    ipa: 'oʊ',
    soundText: 'oh',
    pattern: 'ow',
    exampleWord: 'snow',
    examples: ['snow', 'grow', 'low'],
    tip: 'Long O with ow.',
  },
  {
    id: 'long-o-oe',
    group: 'long-vowels',
    ipa: 'oʊ',
    soundText: 'oh',
    pattern: 'oe',
    exampleWord: 'toe',
    examples: ['toe', 'hoe', 'doe'],
    tip: 'Long O with oe.',
  },
  {
    id: 'long-u-u-e',
    group: 'long-vowels',
    ipa: 'u',
    soundText: 'oo',
    pattern: 'u-e',
    exampleWord: 'tune',
    examples: ['tune', 'rule', 'June'],
    tip: 'Long U with silent e: u-e.',
  },
  {
    id: 'long-u-ue',
    group: 'long-vowels',
    ipa: 'u',
    soundText: 'oo',
    pattern: 'ue',
    exampleWord: 'blue',
    examples: ['blue', 'true', 'glue'],
    tip: 'Long U with ue.',
  },
  {
    id: 'long-u-ew',
    group: 'long-vowels',
    ipa: 'u',
    soundText: 'oo',
    pattern: 'ew',
    exampleWord: 'few',
    examples: ['few', 'new', 'flew'],
    tip: 'Long U with ew.',
  },
  {
    id: 'long-u-ui',
    group: 'long-vowels',
    ipa: 'u',
    soundText: 'oo',
    pattern: 'ui',
    exampleWord: 'fruit',
    examples: ['fruit', 'juice', 'suit'],
    tip: 'Long U with ui.',
  },
];

export function getPronunciationFamilyLabel(sound: PronunciationSound): string {
  const match = /^long-([aeiou])-/.exec(sound.id);
  return match ? `Long ${match[1].toUpperCase()}` : sound.group === 'vowels' ? 'Vowel' : 'Consonant';
}

export function getPronunciationSound(id: string): PronunciationSound | undefined {
  return PRONUNCIATION_SOUNDS.find((sound) => sound.id === id);
}

export function getPronunciationAcceptedWords(target: string): string[] {
  return [target.toLowerCase(), ...(SOUND_ALIASES[target.toLowerCase()] ?? [])];
}

export function scorePronunciationAttempt(target: string, transcript: string): PronunciationAttemptScore {
  const recognizedWords = normalizeSpeechWords(transcript);
  const recognized = recognizedWords.join(' ');
  if (recognizedWords.length === 0) return { score: 0, passed: false, label: 'No speech', recognized };

  const accepted = getPronunciationAcceptedWords(target);
  const best = Math.max(
    ...recognizedWords.flatMap((word) => accepted.map((acceptedWord) => wordSimilarity(acceptedWord, word))),
  );
  const score = Math.round(best * 100);
  const label = score >= 90 ? 'Clear' : score >= 80 ? 'Close' : 'Try again';
  return { score, passed: score >= 90, label, recognized };
}
