/**
 * YouTube Transcript API client (no API key required)
 *
 * This is a fallback for Vercel deployment where yt-dlp is not available.
 * Uses the same API that YouTube's web player uses to fetch captions.
 */

interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

interface TranscriptResponse {
  text: string;
  segments: TranscriptSegment[];
  language: string;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name?: { simpleText?: string };
  kind?: string;
}

/**
 * Extract YouTube video ID from various URL formats
 */
export function extractYouTubeVideoId(url: string): string | null {
  try {
    const urlObj = new URL(url);

    if (urlObj.hostname.includes('youtube.com')) {
      // youtube.com/watch?v=VIDEO_ID
      const videoId = urlObj.searchParams.get('v');
      if (videoId) return videoId;

      // youtube.com/shorts/VIDEO_ID
      const shortsMatch = urlObj.pathname.match(/\/shorts\/([^/?]+)/);
      if (shortsMatch) return shortsMatch[1];
    }

    // youtu.be/VIDEO_ID
    if (urlObj.hostname.includes('youtu.be')) {
      const videoId = urlObj.pathname.slice(1).split('?')[0];
      if (videoId) return videoId;
    }

    // youtube.com/embed/VIDEO_ID
    if (urlObj.pathname.includes('/embed/')) {
      const videoId = urlObj.pathname.split('/embed/')[1]?.split('?')[0];
      if (videoId) return videoId;
    }

    return null;
  } catch {
    return null;
  }
}

/**
 * Extract captionTracks JSON from YouTube page HTML using bracket-counting.
 * More robust than regex for nested JSON structures.
 */
function extractCaptionTracks(html: string): CaptionTrack[] | null {
  const marker = '"captionTracks":';
  const startIdx = html.indexOf(marker);
  if (startIdx === -1) return null;

  let pos = startIdx + marker.length;
  // Skip whitespace
  while (pos < html.length && (html[pos] === ' ' || html[pos] === '\n')) pos++;

  if (html[pos] !== '[') return null;

  // Find matching closing bracket with depth counting
  let depth = 0;
  for (let i = pos; i < html.length; i++) {
    if (html[i] === '[') depth++;
    else if (html[i] === ']') {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(pos, i + 1));
        } catch {
          return null;
        }
      }
    }
  }

  return null;
}

/**
 * Select the best caption track based on language preference.
 * Priority: preferred lang manual > preferred lang auto > any manual > first available
 */
function selectCaptionTrack(tracks: CaptionTrack[], preferredLang = 'en'): CaptionTrack | null {
  if (tracks.length === 0) return null;

  const isAutoGenerated = (track: CaptionTrack) =>
    track.kind === 'asr' || (track.name?.simpleText?.includes('auto-generated') ?? false);

  return (
    tracks.find((t) => t.languageCode === preferredLang && !isAutoGenerated(t)) ||
    tracks.find((t) => t.languageCode === preferredLang) ||
    tracks.find((t) => !isAutoGenerated(t)) ||
    tracks[0]
  );
}

/**
 * Fetch YouTube video transcript using the public API.
 * No authentication required - uses the same endpoint as the YouTube web player.
 * Supports multi-language with English preference.
 */
export async function fetchYouTubeTranscript(videoId: string, preferredLang = 'en'): Promise<TranscriptResponse> {
  const videoPageUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResponse = await fetch(videoPageUrl, {
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      'Accept-Language': 'en-US,en;q=0.9',
    },
    signal: AbortSignal.timeout(15000),
  });

  if (!pageResponse.ok) {
    throw new Error(`Failed to fetch video page: ${pageResponse.status}`);
  }

  const html = await pageResponse.text();

  const captionTracks = extractCaptionTracks(html);
  if (!captionTracks || captionTracks.length === 0) {
    throw new Error('No captions available for this video');
  }

  const track = selectCaptionTrack(captionTracks, preferredLang);
  if (!track) {
    throw new Error('No suitable caption track found');
  }

  const captionResponse = await fetch(track.baseUrl, {
    signal: AbortSignal.timeout(10000),
  });

  if (!captionResponse.ok) {
    throw new Error(`Failed to fetch captions: ${captionResponse.status}`);
  }

  const captionXml = await captionResponse.text();
  const segments = parseYouTubeCaptionXml(captionXml);
  const text = segments.map((s) => s.text).join(' ');

  return {
    text,
    segments,
    language: track.languageCode,
  };
}

/**
 * Parse YouTube caption XML format
 */
function parseYouTubeCaptionXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const textRegex = /<text start="([^"]+)" dur="([^"]+)"[^>]*>([^<]*)<\/text>/g;
  const matches = Array.from(xml.matchAll(textRegex));

  for (const match of matches) {
    const start = parseFloat(match[1]);
    const duration = parseFloat(match[2]);
    let text = match[3];

    text = text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&nbsp;/g, ' ')
      .trim();

    if (text) {
      segments.push({ text, start, duration });
    }
  }

  return segments;
}

/**
 * Fetch YouTube video metadata using oEmbed API (no auth required)
 */
export async function fetchYouTubeMetadata(url: string): Promise<{
  title: string;
  author_name?: string;
  thumbnail_url?: string;
}> {
  const oembedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(url)}&format=json`;
  const response = await fetch(oembedUrl, {
    signal: AbortSignal.timeout(10000),
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch video metadata: ${response.status}`);
  }

  return response.json();
}
