import { expect, test } from '@playwright/test';
import { importWordbook } from './helpers/material-import';

test('imports a personal word book, recalls, spells, reviews construction and saves an example',async({page})=>{
  await page.setViewportSize({width:375,height:850});
  await page.goto('/dashboard'); await page.locator('main[data-seeded="true"]').waitFor({timeout:60000});
  await importWordbook(page, 'Personal test words', 'word,meaning,example\nhelpful,有帮助的,A helpful reply.');
  const bookHref = await page.evaluate(async()=>new Promise<string>((resolve,reject)=>{const req=indexedDB.open('echotype:anonymous');req.onsuccess=()=>{const database=req.result;const get=database.transaction('contents').objectStore('contents').getAll();get.onsuccess=()=>{const word=get.result.find(w=>w.metadata?.vocabulary);database.close();word?resolve('/library/vocabulary?book='+encodeURIComponent(word.category)):reject('Missing import');};};req.onerror=()=>reject(req.error);}));
  await page.goto(bookHref);
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await expect(page.getByText('有帮助的',{exact:true})).not.toBeVisible();
  await page.getByLabel('Your answer',{exact:true}).fill('useful to another person');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await expect(page.getByText('有帮助的',{exact:true})).toBeVisible();
  await page.reload();
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await expect(page.getByLabel('Your answer',{exact:true})).toHaveValue('useful to another person');
  await expect(page.getByLabel('Your answer',{exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Good',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Back to word book',exact:true}).click();
  await page.getByLabel('Practice mode',{exact:true}).selectOption('spelling');
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await page.getByLabel('Your answer',{exact:true}).fill('helpfull');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await expect(page.getByRole('button',{name:'Good',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Again',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Back to word book',exact:true}).click();
  await page.getByLabel('Practice mode',{exact:true}).selectOption('construction');
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await page.getByLabel('Your answer',{exact:true}).fill('help + ful');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await expect(page.getByRole('link',{name:'Construction reference',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Good',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Back to word book',exact:true}).click();
  await page.getByLabel('Practice mode',{exact:true}).selectOption('application');
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await page.getByLabel('New situation',{exact:true}).fill('Helping a customer choose a bicycle');
  await page.getByLabel('Your answer',{exact:true}).fill('A helpful reply.');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await expect(page.getByRole('alert').filter({hasText:'Use the word'})).toBeVisible();
  await expect(page.getByLabel('Your answer',{exact:true})).toBeEnabled();
  await page.getByLabel('Your answer',{exact:true}).fill('This helpful guide explains how to choose a bicycle.');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await page.getByRole('button',{name:'Save to my notes',exact:true}).click();
  await expect(page.getByText('Saved to my notes.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Good',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('file import, daily deep link, recall scheduling and construction coverage',async({page})=>{
  await page.goto('/dashboard');await page.locator('main[data-seeded="true"]').waitFor({timeout:60000});
  await importWordbook(page, 'Own words', 'word\tmeaning\texample\nhelpful\t有帮助的\tA helpful reply.\nuncle\t叔叔\tMy uncle is here.');
  const bookHref = await page.evaluate(async()=>new Promise<string>((resolve,reject)=>{const req=indexedDB.open('echotype:anonymous');req.onsuccess=()=>{const database=req.result;const get=database.transaction('contents').objectStore('contents').getAll();get.onsuccess=()=>{const word=get.result.find(w=>w.metadata?.vocabulary);database.close();word?resolve('/library/vocabulary?book='+encodeURIComponent(word.category)):reject('Missing import');};};req.onerror=()=>reject(req.error);}));
  await page.goto(bookHref);
  const id=await page.evaluate(async()=>new Promise<string>((resolve,reject)=>{const req=indexedDB.open('echotype:anonymous');req.onsuccess=()=>{const db=req.result;const tx=db.transaction('contents','readonly');const get=tx.objectStore('contents').getAll();get.onsuccess=()=>{const word=get.result.find(w=>w.metadata?.vocabulary?.bookTitle==='Own words'&&w.title==='helpful');db.close();word?resolve(word.id):reject('word missing');};};req.onerror=()=>reject(req.error);}));
  await page.goto(`/library/vocabulary?word=${encodeURIComponent(id)}&mode=meaning`);
  await page.getByLabel('Your answer',{exact:true}).fill('giving useful help');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await page.getByRole('button',{name:'Again',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  await page.goto(`/library/vocabulary?word=${encodeURIComponent(id)}&mode=meaning`);
  await expect(page.getByText('This word is not due or is unavailable in this mode. Choose another task.',{exact:true})).toBeVisible();
  await page.getByLabel('Practice mode',{exact:true}).selectOption('dictation');
  await page.goto(`/library/vocabulary?word=${encodeURIComponent(id)}&mode=dictation`);
  await expect(page.getByRole('heading',{name:'Listen to the word',exact:true})).toBeVisible();
  await expect(page.getByText('有帮助的',{exact:true})).not.toBeVisible();
  await page.getByLabel('Your answer',{exact:true}).fill('helpful');
  await page.getByRole('button',{name:'Compare answer',exact:true}).click();
  await page.getByRole('button',{name:'Good',exact:true}).click();
  await expect(page.getByText('Saved. Next review:',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Back to word book',exact:true}).click();
  await page.getByLabel('Practice mode',{exact:true}).selectOption('construction');
  await page.getByRole('button',{name:'Start vocabulary practice',exact:true}).click();
  await expect(page.getByRole('heading',{name:'uncle',exact:true})).not.toBeVisible();
});
