import type { WordBook } from '@/types/wordbook';

export const scenarioBooks: WordBook[] = [
  {
    id: 'airport',
    name: '机场 / 飞机',
    nameEn: 'Airport & Flights',
    description: 'Complete airport phrases from check-in to arrival — never get lost or confused at the airport again.',
    kind: 'scenario',
    emoji: '✈️',
    difficulty: 'beginner',
    filterTag: 'Travel',
    tags: ['travel', 'airport', 'flights'],
    items: [
      { title: 'Check-in bags', text: 'I would like to check in two bags, please.', type: 'phrase', category: 'airport', tags: ['airport', 'checkin'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Window seat', text: 'Could I have a window seat, please?', type: 'phrase', category: 'airport', tags: ['airport', 'seat'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Flight delayed', text: 'Is the flight to London still on time?', type: 'phrase', category: 'airport', tags: ['airport', 'delay'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Boarding gate', text: 'Excuse me, where is the boarding gate for flight CA123?', type: 'phrase', category: 'airport', tags: ['airport', 'boarding'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Passport control', text: 'Please have your passport and boarding pass ready.', type: 'sentence', category: 'airport', tags: ['airport', 'passport'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Purpose of visit', text: 'What is the purpose of your visit to the country?', type: 'sentence', category: 'airport', tags: ['airport', 'customs'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Declare items', text: 'Do you have anything to declare at customs?', type: 'phrase', category: 'airport', tags: ['airport', 'customs'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Missed flight', text: 'I missed my connecting flight. Can you help me rebook?', type: 'sentence', category: 'airport', tags: ['airport', 'rebooking'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Luggage lost', text: 'My luggage did not arrive. Where can I report it?', type: 'sentence', category: 'airport', tags: ['airport', 'baggage'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Carry-on limit', text: 'What is the carry-on baggage weight limit for this flight?', type: 'phrase', category: 'airport', tags: ['airport', 'baggage'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Boarding announcement', text: 'We are now boarding rows twenty and above.', type: 'sentence', category: 'airport', tags: ['airport', 'boarding'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Fasten seatbelt', text: 'Please fasten your seatbelt and turn off all electronic devices.', type: 'sentence', category: 'airport', tags: ['airport', 'inflight'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Meal choice', text: 'Would you prefer the chicken or the vegetarian meal?', type: 'phrase', category: 'airport', tags: ['airport', 'inflight'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Arrival card', text: 'Please fill out the arrival card before landing.', type: 'sentence', category: 'airport', tags: ['airport', 'arrival'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Taxi to city', text: 'How do I get a taxi to the city center from here?', type: 'phrase', category: 'airport', tags: ['airport', 'transport'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Currency exchange', text: 'Is there a currency exchange counter in this terminal?', type: 'phrase', category: 'airport', tags: ['airport', 'money'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Security check', text: 'Please remove your laptop and liquids from your bag.', type: 'sentence', category: 'airport', tags: ['airport', 'security'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Upgrade request', text: 'Is there any possibility of upgrading to business class?', type: 'phrase', category: 'airport', tags: ['airport', 'upgrade'], source: 'builtin', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'restaurant',
    name: '餐厅 / 点餐',
    nameEn: 'Restaurant & Dining',
    description: 'From making reservations to paying the bill — dine out with complete confidence in English.',
    kind: 'scenario',
    emoji: '🍽️',
    difficulty: 'beginner',
    filterTag: 'Food & Drink',
    tags: ['food', 'restaurant', 'dining'],
    items: [
      { title: 'Reservation', text: 'I have a reservation for two under the name Wang.', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'booking'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Table for two', text: 'Could we have a table for two, please?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'seating'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Menu please', text: 'Could I see the menu, please?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Recommend dish', text: 'What do you recommend for a main course?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Order ready', text: 'Are you ready to order, or do you need a few more minutes?', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Allergies', text: 'I am allergic to nuts. Does this dish contain any?', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'dietary'], source: 'builtin', difficulty: 'beginner' },
      { title: 'No meat', text: 'I am vegetarian. Could you suggest something without meat?', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'dietary'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Cooking level', text: 'How would you like your steak? Rare, medium, or well done?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Extra napkin', text: 'Could I have some extra napkins, please?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'service'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Too spicy', text: 'Could you make it less spicy? I cannot handle too much heat.', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'preference'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Check please', text: 'Could we have the check, please? We are in a bit of a hurry.', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'payment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Split the bill', text: 'Could we pay separately? We would like to split the bill.', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'payment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Credit card', text: 'Do you accept credit cards, or is it cash only?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'payment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Compliment food', text: 'The food was absolutely delicious, thank you so much.', type: 'sentence', category: 'restaurant', tags: ['restaurant', 'compliment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Takeaway box', text: 'Could I have a box to take the rest home?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'takeaway'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Wrong order', text: 'Excuse me, I think you brought the wrong dish.', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'complaint'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Water refill', text: 'Could you please refill my water glass?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'service'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Outdoor seat', text: 'Do you have any outdoor seating available?', type: 'phrase', category: 'restaurant', tags: ['restaurant', 'seating'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'hotel',
    name: '酒店 / 住宿',
    nameEn: 'Hotel & Accommodation',
    description: 'Everything you need for hotel check-in, room service, complaints, and check-out in English.',
    kind: 'scenario',
    emoji: '🏨',
    difficulty: 'beginner',
    filterTag: 'Travel',
    tags: ['travel', 'hotel', 'accommodation'],
    items: [
      { title: 'Check in', text: 'I have a reservation. My name is Zhang Wei.', type: 'phrase', category: 'hotel', tags: ['hotel', 'checkin'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Room type', text: 'I booked a standard double room for three nights.', type: 'phrase', category: 'hotel', tags: ['hotel', 'checkin'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Early check-in', text: 'Is it possible to check in a few hours early?', type: 'phrase', category: 'hotel', tags: ['hotel', 'checkin'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Room key', text: 'Here are your key cards. Your room is on the fifth floor.', type: 'sentence', category: 'hotel', tags: ['hotel', 'room'], source: 'builtin', difficulty: 'beginner' },
      { title: 'WiFi password', text: 'Could you give me the WiFi password, please?', type: 'phrase', category: 'hotel', tags: ['hotel', 'service'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Room service', text: 'I would like to order room service. What is available now?', type: 'sentence', category: 'hotel', tags: ['hotel', 'service'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Extra towels', text: 'Could you send up some extra towels to room five one two?', type: 'sentence', category: 'hotel', tags: ['hotel', 'housekeeping'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Noise complaint', text: 'I am sorry to bother you, but the room next door is very noisy.', type: 'sentence', category: 'hotel', tags: ['hotel', 'complaint'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Air conditioning', text: 'The air conditioning in my room does not seem to be working.', type: 'sentence', category: 'hotel', tags: ['hotel', 'complaint'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Breakfast time', text: 'What time does breakfast start and end in the morning?', type: 'phrase', category: 'hotel', tags: ['hotel', 'dining'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Late checkout', text: 'Is it possible to arrange a late checkout until two pm?', type: 'phrase', category: 'hotel', tags: ['hotel', 'checkout'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Check out', text: 'I would like to check out. Could you prepare my bill please?', type: 'sentence', category: 'hotel', tags: ['hotel', 'checkout'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Luggage storage', text: 'Could you store my luggage until my flight at six this evening?', type: 'sentence', category: 'hotel', tags: ['hotel', 'storage'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Airport shuttle', text: 'Does the hotel provide an airport shuttle service?', type: 'phrase', category: 'hotel', tags: ['hotel', 'transport'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Local attraction', text: 'Could you recommend some must-see attractions nearby?', type: 'phrase', category: 'hotel', tags: ['hotel', 'concierge'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Charging adapter', text: 'Do you have a universal charging adapter I could borrow?', type: 'phrase', category: 'hotel', tags: ['hotel', 'amenity'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'shopping',
    name: '购物 / 商场',
    nameEn: 'Shopping & Malls',
    description: 'Browse, try on, bargain, and return items — master the full shopping experience in English.',
    kind: 'scenario',
    emoji: '🛍️',
    difficulty: 'beginner',
    filterTag: 'Daily Life',
    tags: ['shopping', 'retail', 'daily'],
    items: [
      { title: 'Looking around', text: 'I am just browsing, thank you. I will let you know if I need help.', type: 'sentence', category: 'shopping', tags: ['shopping', 'greeting'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Item location', text: 'Excuse me, where can I find the sports section?', type: 'phrase', category: 'shopping', tags: ['shopping', 'navigation'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Size available', text: 'Do you have this in a medium or large?', type: 'phrase', category: 'shopping', tags: ['shopping', 'sizing'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Try on', text: 'Could I try this on? Where is the fitting room?', type: 'phrase', category: 'shopping', tags: ['shopping', 'fitting'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Different color', text: 'Do you have this jacket in black or navy blue?', type: 'phrase', category: 'shopping', tags: ['shopping', 'color'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Price check', text: 'How much does this cost? Is the price tag still on it?', type: 'phrase', category: 'shopping', tags: ['shopping', 'price'], source: 'builtin', difficulty: 'beginner' },
      { title: 'On sale', text: 'Is this item on sale? I saw a sign for fifty percent off.', type: 'phrase', category: 'shopping', tags: ['shopping', 'discount'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Bargain', text: 'That is a little over my budget. Could you do a better price?', type: 'sentence', category: 'shopping', tags: ['shopping', 'bargain'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Gift wrap', text: 'Could you gift wrap this for me? It is a present.', type: 'phrase', category: 'shopping', tags: ['shopping', 'gift'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Payment method', text: 'Do you accept Alipay or WeChat Pay here?', type: 'phrase', category: 'shopping', tags: ['shopping', 'payment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Return policy', text: 'What is the return policy if the item does not fit?', type: 'phrase', category: 'shopping', tags: ['shopping', 'return'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Exchange item', text: 'I bought this yesterday but it is the wrong size. Can I exchange it?', type: 'sentence', category: 'shopping', tags: ['shopping', 'exchange'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Tax refund', text: 'Can I claim a tax refund on this as a foreign visitor?', type: 'phrase', category: 'shopping', tags: ['shopping', 'tax'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Closing time', text: 'What time does the store close today?', type: 'phrase', category: 'shopping', tags: ['shopping', 'info'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Out of stock', text: 'I am sorry, that item is currently out of stock.', type: 'sentence', category: 'shopping', tags: ['shopping', 'stock'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'directions',
    name: '问路 / 交通',
    nameEn: 'Directions & Transport',
    description: 'Ask for and understand directions, navigate public transport, and hail a taxi with ease.',
    kind: 'scenario',
    emoji: '🗺️',
    difficulty: 'beginner',
    filterTag: 'Travel',
    tags: ['travel', 'directions', 'transport'],
    items: [
      { title: 'Ask directions', text: 'Excuse me, could you tell me how to get to the city center?', type: 'phrase', category: 'directions', tags: ['directions', 'asking'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Turn left', text: 'Turn left at the traffic lights and walk for five minutes.', type: 'sentence', category: 'directions', tags: ['directions', 'giving'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Straight ahead', text: 'Go straight ahead and then take the second right.', type: 'sentence', category: 'directions', tags: ['directions', 'giving'], source: 'builtin', difficulty: 'beginner' },
      { title: 'How far', text: 'How far is it from here? Can I walk or should I take a bus?', type: 'phrase', category: 'directions', tags: ['directions', 'distance'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Nearest subway', text: 'Where is the nearest subway station, please?', type: 'phrase', category: 'directions', tags: ['directions', 'metro'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Which bus', text: 'Which bus do I take to get to the museum?', type: 'phrase', category: 'directions', tags: ['directions', 'bus'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Last stop', text: 'Could you let me know when we reach the last stop?', type: 'sentence', category: 'directions', tags: ['directions', 'bus'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Transfer line', text: 'I need to transfer at this station to line three.', type: 'sentence', category: 'directions', tags: ['directions', 'metro'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Hail a cab', text: 'Can you hail a cab for me? I need to go to the airport.', type: 'phrase', category: 'directions', tags: ['directions', 'taxi'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Taxi address', text: 'Please take me to this address. Here it is on my phone.', type: 'sentence', category: 'directions', tags: ['directions', 'taxi'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Too far to walk', text: 'It is too far to walk. You should take the bus or subway.', type: 'sentence', category: 'directions', tags: ['directions', 'advice'], source: 'builtin', difficulty: 'beginner' },
      { title: 'On the right', text: 'The post office is on your right, next to the pharmacy.', type: 'sentence', category: 'directions', tags: ['directions', 'landmark'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Missed stop', text: 'I think I missed my stop. What should I do now?', type: 'phrase', category: 'directions', tags: ['directions', 'problem'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Map app', text: 'Let me use a map app to find the best route for you.', type: 'sentence', category: 'directions', tags: ['directions', 'tech'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Ride-sharing', text: 'I ordered a ride-sharing car. It should arrive in three minutes.', type: 'sentence', category: 'directions', tags: ['directions', 'rideshare'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'interview',
    name: '面试 / 求职',
    nameEn: 'Job Interview',
    description: 'From self-introduction to salary negotiation — ace your next English-language job interview.',
    kind: 'scenario',
    emoji: '👔',
    difficulty: 'intermediate',
    filterTag: 'Business',
    tags: ['career', 'interview', 'professional'],
    items: [
      { title: 'Self introduction', text: 'Thank you for having me. My name is Li Ming and I have five years of experience in software development.', type: 'sentence', category: 'interview', tags: ['interview', 'intro'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Strengths', text: 'My greatest strength is my ability to work well under pressure and meet tight deadlines.', type: 'sentence', category: 'interview', tags: ['interview', 'strengths'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Weakness', text: 'One area I am working to improve is public speaking, and I have been taking courses to build my confidence.', type: 'sentence', category: 'interview', tags: ['interview', 'weakness'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Why this company', text: 'I admire your company culture and I believe my skills align well with your team goals.', type: 'sentence', category: 'interview', tags: ['interview', 'motivation'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Career goal', text: 'In five years, I hope to take on a leadership role and contribute to high-impact projects.', type: 'sentence', category: 'interview', tags: ['interview', 'goals'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Team experience', text: 'I thrive in collaborative environments and have led cross-functional teams of up to ten people.', type: 'sentence', category: 'interview', tags: ['interview', 'teamwork'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Problem solving', text: 'When I face a difficult problem, I break it down into smaller steps and look for the root cause first.', type: 'sentence', category: 'interview', tags: ['interview', 'skills'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Salary expectation', text: 'Based on my experience and market research, I am looking for a salary in the range of twenty to twenty-five thousand per month.', type: 'sentence', category: 'interview', tags: ['interview', 'salary'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Ask about role', text: 'Could you tell me more about the day-to-day responsibilities of this position?', type: 'phrase', category: 'interview', tags: ['interview', 'question'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Company culture', text: 'How would you describe the company culture and work environment here?', type: 'phrase', category: 'interview', tags: ['interview', 'question'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Growth opportunity', text: 'What opportunities are there for professional development and career growth?', type: 'phrase', category: 'interview', tags: ['interview', 'question'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Start date', text: 'I can start as soon as two weeks after receiving the offer.', type: 'sentence', category: 'interview', tags: ['interview', 'logistics'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Reference', text: 'I can provide references from my previous manager and team members if needed.', type: 'sentence', category: 'interview', tags: ['interview', 'reference'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Thank you', text: 'Thank you so much for your time today. I look forward to hearing from you.', type: 'sentence', category: 'interview', tags: ['interview', 'closing'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Remote work', text: 'Is there flexibility to work remotely, at least part of the time?', type: 'phrase', category: 'interview', tags: ['interview', 'workmode'], source: 'builtin', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'hospital',
    name: '医院 / 看病',
    nameEn: 'Hospital & Medical',
    description: 'Describe symptoms, talk to doctors, and understand prescriptions — stay safe in any English-speaking country.',
    kind: 'scenario',
    emoji: '🏥',
    difficulty: 'beginner',
    filterTag: 'Health',
    tags: ['health', 'hospital', 'medical'],
    items: [
      { title: 'Make appointment', text: 'I would like to make an appointment to see a doctor.', type: 'phrase', category: 'hospital', tags: ['hospital', 'appointment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Describe symptoms', text: 'I have had a sore throat and high fever for two days.', type: 'sentence', category: 'hospital', tags: ['hospital', 'symptoms'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Headache', text: 'I have a terrible headache and I feel dizzy.', type: 'phrase', category: 'hospital', tags: ['hospital', 'symptoms'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Stomachache', text: 'I have been having severe stomach pain since this morning.', type: 'sentence', category: 'hospital', tags: ['hospital', 'symptoms'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Medical history', text: 'I have no known allergies and no serious medical history.', type: 'sentence', category: 'hospital', tags: ['hospital', 'history'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Prescription', text: 'The doctor gave me a prescription for antibiotics.', type: 'sentence', category: 'hospital', tags: ['hospital', 'medicine'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Dosage', text: 'How often should I take this medicine and with or without food?', type: 'phrase', category: 'hospital', tags: ['hospital', 'medicine'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Blood test', text: 'The doctor recommended a blood test to check my health.', type: 'sentence', category: 'hospital', tags: ['hospital', 'test'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Side effects', text: 'What are the possible side effects of this medication?', type: 'phrase', category: 'hospital', tags: ['hospital', 'medicine'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Insurance', text: 'Do you accept international health insurance here?', type: 'phrase', category: 'hospital', tags: ['hospital', 'payment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Rest advised', text: 'The doctor advised me to rest at home for three days.', type: 'sentence', category: 'hospital', tags: ['hospital', 'advice'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Emergency room', text: 'I need to go to the emergency room. This is urgent.', type: 'phrase', category: 'hospital', tags: ['hospital', 'emergency'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Follow up', text: 'Please come back for a follow-up appointment next week.', type: 'sentence', category: 'hospital', tags: ['hospital', 'appointment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Pain level', text: 'On a scale of one to ten, how would you rate the pain?', type: 'phrase', category: 'hospital', tags: ['hospital', 'assessment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Get well', text: 'Take good care of yourself and get plenty of rest.', type: 'sentence', category: 'hospital', tags: ['hospital', 'wellbeing'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'social',
    name: '社交 / 聚会',
    nameEn: 'Social & Gatherings',
    description: 'Make friends, attend parties, and navigate social situations with natural, confident English.',
    kind: 'scenario',
    emoji: '🎉',
    difficulty: 'beginner',
    filterTag: 'Social',
    tags: ['social', 'friends', 'party'],
    items: [
      { title: 'Small talk', text: 'What do you do for work? Have you lived here long?', type: 'phrase', category: 'social', tags: ['social', 'smalltalk'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Introduce friend', text: 'Let me introduce you to my colleague Tom. He is from Shanghai.', type: 'sentence', category: 'social', tags: ['social', 'intro'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Nice to meet', text: 'It is so nice to finally meet you in person!', type: 'phrase', category: 'social', tags: ['social', 'greeting'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Compliment', text: 'I love your outfit! Where did you get it?', type: 'phrase', category: 'social', tags: ['social', 'compliment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Invite to event', text: 'We are having a small gathering on Saturday. Would you like to come?', type: 'sentence', category: 'social', tags: ['social', 'invitation'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Accept invite', text: 'That sounds great! I would love to come. What time should I arrive?', type: 'sentence', category: 'social', tags: ['social', 'invitation'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Decline politely', text: 'I really appreciate the invitation, but I already have plans that evening.', type: 'sentence', category: 'social', tags: ['social', 'declining'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Common interest', text: 'Oh, you like hiking too? We should go together sometime!', type: 'sentence', category: 'social', tags: ['social', 'interest'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Exchange contact', text: 'It was great meeting you. Can we exchange contact information?', type: 'sentence', category: 'social', tags: ['social', 'networking'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Toast', text: 'Let us raise a glass and toast to health and happiness!', type: 'sentence', category: 'social', tags: ['social', 'party'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Catch up', text: 'It has been so long! What have you been up to lately?', type: 'phrase', category: 'social', tags: ['social', 'catchup'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Saying goodbye', text: 'It was wonderful seeing you again. Let us not leave it so long next time.', type: 'sentence', category: 'social', tags: ['social', 'farewell'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Thank host', text: 'Thank you so much for having us. The food was amazing.', type: 'sentence', category: 'social', tags: ['social', 'gratitude'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Weekend plans', text: 'Any exciting plans for the weekend? Are you doing anything fun?', type: 'phrase', category: 'social', tags: ['social', 'smalltalk'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Keep in touch', text: 'Let us keep in touch! I will message you on WeChat.', type: 'sentence', category: 'social', tags: ['social', 'networking'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'coffee-shop',
    name: '咖啡馆',
    nameEn: 'Coffee Shop',
    description: 'Order your perfect coffee, customize your drink, and chat with baristas like a local.',
    kind: 'scenario',
    emoji: '☕',
    difficulty: 'beginner',
    filterTag: 'Food & Drink',
    tags: ['food', 'coffee', 'casual'],
    items: [
      { title: 'Order coffee', text: 'Could I get a medium latte with oat milk, please?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Customization', text: 'Could you make that with less sugar and extra foam?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'customization'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Hot or cold', text: 'Would you like that hot or iced?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Name for order', text: 'Can I get a name for the order? It is for Li Ming.', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Eat in or takeout', text: 'Is this to have here or to take away?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'ordering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Food pairing', text: 'I will also have a blueberry muffin to go with that.', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'food'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Loyalty card', text: 'Do you have a loyalty card? Every tenth coffee is free.', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'loyalty'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Table request', text: 'Is it okay if I work here for a couple of hours?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'workspace'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Wrong drink', text: 'Excuse me, I ordered a cappuccino but I think this is an Americano.', type: 'sentence', category: 'coffee-shop', tags: ['coffee', 'complaint'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Compliment barista', text: 'This is the best coffee I have had in a long time. Thank you!', type: 'sentence', category: 'coffee-shop', tags: ['coffee', 'compliment'], source: 'builtin', difficulty: 'beginner' },
      { title: 'WiFi request', text: 'Do you have free WiFi here? What is the password?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'wifi'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Closing time', text: 'What time do you close today? I want to stay a bit longer.', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'hours'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Seasonal drink', text: 'What is your seasonal special? Is there anything new on the menu?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'menu'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Dairy free', text: 'I am lactose intolerant. Do you offer any dairy-free milk options?', type: 'sentence', category: 'coffee-shop', tags: ['coffee', 'dietary'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Refill request', text: 'Could I get a refill on my drip coffee, please?', type: 'phrase', category: 'coffee-shop', tags: ['coffee', 'service'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'campus',
    name: '校园生活',
    nameEn: 'Campus Life',
    description: 'Classroom discussions, study groups, dorm life — thrive in any English-speaking campus environment.',
    kind: 'scenario',
    emoji: '🎓',
    difficulty: 'beginner',
    filterTag: 'Social',
    tags: ['education', 'campus', 'student'],
    items: [
      { title: 'Ask professor', text: 'Professor, could I ask you a question about the assignment?', type: 'phrase', category: 'campus', tags: ['campus', 'classroom'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Office hours', text: 'When are your office hours? I would like to discuss my grade.', type: 'phrase', category: 'campus', tags: ['campus', 'academic'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Study group', text: 'Would you like to form a study group for the upcoming exam?', type: 'phrase', category: 'campus', tags: ['campus', 'studying'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Library book', text: 'Excuse me, how do I renew a library book online?', type: 'phrase', category: 'campus', tags: ['campus', 'library'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Late assignment', text: 'I am sorry, but I was sick. Could I submit the assignment late?', type: 'sentence', category: 'campus', tags: ['campus', 'academic'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Course enrollment', text: 'Is it possible to add this course? I know enrollment just closed.', type: 'sentence', category: 'campus', tags: ['campus', 'enrollment'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Dormitory rules', text: 'What are the quiet hours in the dormitory?', type: 'phrase', category: 'campus', tags: ['campus', 'dorm'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Roommate request', text: 'My roommate and I have some differences. Who do I talk to?', type: 'sentence', category: 'campus', tags: ['campus', 'dorm'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Club join', text: 'I am interested in joining the debate club. How do I sign up?', type: 'sentence', category: 'campus', tags: ['campus', 'activities'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Campus directions', text: 'Excuse me, could you tell me where the engineering building is?', type: 'phrase', category: 'campus', tags: ['campus', 'navigation'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Group presentation', text: 'For our group project, I will handle the introduction and data analysis.', type: 'sentence', category: 'campus', tags: ['campus', 'presentation'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Cafeteria food', text: 'The cafeteria menu changes every day. Today they have hot pot.', type: 'sentence', category: 'campus', tags: ['campus', 'food'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Scholarship info', text: 'Where can I find information about available scholarships?', type: 'phrase', category: 'campus', tags: ['campus', 'financial'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Exam schedule', text: 'When is the final exam schedule released for this semester?', type: 'phrase', category: 'campus', tags: ['campus', 'exam'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Graduation plan', text: 'I am planning to apply for graduate school after I finish my degree.', type: 'sentence', category: 'campus', tags: ['campus', 'future'], source: 'builtin', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'phone-call',
    name: '电话通话',
    nameEn: 'Phone Calls',
    description: 'Answer calls, transfer calls, leave voicemails, and run conference calls — all in fluent English.',
    kind: 'scenario',
    emoji: '📞',
    difficulty: 'beginner',
    filterTag: 'Business',
    tags: ['communication', 'phone', 'business'],
    items: [
      { title: 'Answer phone', text: 'Hello, this is Li Ming speaking. How can I help you?', type: 'sentence', category: 'phone-call', tags: ['phone', 'answering'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Wrong number', text: 'I am sorry, I think you have the wrong number.', type: 'phrase', category: 'phone-call', tags: ['phone', 'mistake'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Hold please', text: 'Could you please hold for a moment? I will transfer you now.', type: 'sentence', category: 'phone-call', tags: ['phone', 'transfer'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Leave message', text: 'I am afraid she is not available. Can I take a message?', type: 'sentence', category: 'phone-call', tags: ['phone', 'message'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Call back', text: 'Could you ask him to call me back at his earliest convenience?', type: 'sentence', category: 'phone-call', tags: ['phone', 'callback'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Bad connection', text: 'I am sorry, the line is not very clear. Could you repeat that?', type: 'sentence', category: 'phone-call', tags: ['phone', 'clarity'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Spell name', text: 'Could you spell your name for me, please?', type: 'phrase', category: 'phone-call', tags: ['phone', 'confirm'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Reason for call', text: 'I am calling to enquire about your services and pricing.', type: 'sentence', category: 'phone-call', tags: ['phone', 'purpose'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Conference call', text: 'We are scheduling a conference call for all team members on Thursday.', type: 'sentence', category: 'phone-call', tags: ['phone', 'business'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'End call politely', text: 'Thank you so much for your time today. Have a great day!', type: 'sentence', category: 'phone-call', tags: ['phone', 'closing'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Voicemail', text: 'Hi, you have reached John. Please leave a message after the beep.', type: 'sentence', category: 'phone-call', tags: ['phone', 'voicemail'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Confirm details', text: 'Let me confirm your booking details. That is a table for four at seven pm.', type: 'sentence', category: 'phone-call', tags: ['phone', 'confirmation'], source: 'builtin', difficulty: 'beginner' },
      { title: 'No answer', text: 'I called several times but there was no answer. Could you try again?', type: 'sentence', category: 'phone-call', tags: ['phone', 'follow-up'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Telephone number', text: 'Could I get a direct telephone number where I can reach you?', type: 'phrase', category: 'phone-call', tags: ['phone', 'contact'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Mute and unmute', text: 'Sorry, I was on mute. Could you repeat your last point?', type: 'sentence', category: 'phone-call', tags: ['phone', 'meeting'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
  {
    id: 'bank-post',
    name: '银行 / 邮局',
    nameEn: 'Bank & Post Office',
    description: 'Open bank accounts, send parcels, exchange currency, and handle everyday financial tasks in English.',
    kind: 'scenario',
    emoji: '🏦',
    difficulty: 'beginner',
    filterTag: 'Daily Life',
    tags: ['financial', 'bank', 'post'],
    items: [
      { title: 'Open account', text: 'I would like to open a savings account, please.', type: 'phrase', category: 'bank-post', tags: ['bank', 'account'], source: 'builtin', difficulty: 'beginner' },
      { title: 'ID required', text: 'We will need your passport and proof of address to open an account.', type: 'sentence', category: 'bank-post', tags: ['bank', 'requirements'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Withdraw cash', text: 'I would like to withdraw five hundred dollars in cash, please.', type: 'phrase', category: 'bank-post', tags: ['bank', 'withdrawal'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Wire transfer', text: 'I need to send an international wire transfer to the following account.', type: 'sentence', category: 'bank-post', tags: ['bank', 'transfer'], source: 'builtin', difficulty: 'intermediate' },
      { title: 'Exchange rate', text: 'What is the current exchange rate for US dollars to Chinese yuan?', type: 'phrase', category: 'bank-post', tags: ['bank', 'exchange'], source: 'builtin', difficulty: 'beginner' },
      { title: 'ATM location', text: 'Is there an ATM nearby where I can withdraw some cash?', type: 'phrase', category: 'bank-post', tags: ['bank', 'atm'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Card blocked', text: 'My card was blocked after I entered the wrong PIN. Can you help?', type: 'sentence', category: 'bank-post', tags: ['bank', 'problem'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Check balance', text: 'Could you please check the balance on my account?', type: 'phrase', category: 'bank-post', tags: ['bank', 'balance'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Send parcel', text: 'I would like to send this parcel to the United States by express mail.', type: 'sentence', category: 'bank-post', tags: ['post', 'sending'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Parcel weight', text: 'Could you weigh this package for me and tell me the shipping cost?', type: 'phrase', category: 'bank-post', tags: ['post', 'weight'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Registered mail', text: 'I would like to send this by registered mail with tracking.', type: 'phrase', category: 'bank-post', tags: ['post', 'registered'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Collect parcel', text: 'I received a notice that I have a parcel to collect.', type: 'sentence', category: 'bank-post', tags: ['post', 'collection'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Fragile items', text: 'Please mark this package as fragile. The contents are breakable.', type: 'sentence', category: 'bank-post', tags: ['post', 'handling'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Delivery time', text: 'How long will it take for this parcel to arrive in the UK?', type: 'phrase', category: 'bank-post', tags: ['post', 'delivery'], source: 'builtin', difficulty: 'beginner' },
      { title: 'Monthly statement', text: 'Could I get a copy of my account statement for last month?', type: 'phrase', category: 'bank-post', tags: ['bank', 'statement'], source: 'builtin', difficulty: 'beginner' },
    ],
  },
];
