import AsyncStorage from '@react-native-async-storage/async-storage';
import { cardToData, createNewCard } from '@/lib/fsrs';
import type { Content, ContentType, DifficultyLevel } from '@/types/content';

const SEED_KEY = 'echotype_mobile_seeded_v1';

interface SeedItem {
  title: string;
  text: string;
  type: ContentType;
  tags: string[];
  difficulty: DifficultyLevel;
  category?: string;
}

const builtinWords: SeedItem[] = [
  {
    title: 'hello',
    text: 'hello',
    type: 'word',
    tags: ['greeting', 'noun'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'world',
    text: 'world',
    type: 'word',
    tags: ['basic', 'noun'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'computer',
    text: 'computer',
    type: 'word',
    tags: ['technology', 'noun'],
    difficulty: 'beginner',
    category: 'technology',
  },
  {
    title: 'language',
    text: 'language',
    type: 'word',
    tags: ['education', 'noun'],
    difficulty: 'beginner',
    category: 'education',
  },
  {
    title: 'practice',
    text: 'practice',
    type: 'word',
    tags: ['education', 'verb'],
    difficulty: 'beginner',
    category: 'education',
  },
  {
    title: 'beautiful',
    text: 'beautiful',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'important',
    text: 'important',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'understand',
    text: 'understand',
    type: 'word',
    tags: ['verb'],
    difficulty: 'beginner',
    category: 'education',
  },
  {
    title: 'appreciate',
    text: 'appreciate',
    type: 'word',
    tags: ['verb', 'emotions'],
    difficulty: 'beginner',
    category: 'emotions',
  },
  {
    title: 'schedule',
    text: 'schedule',
    type: 'word',
    tags: ['noun', 'verb'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'comfortable',
    text: 'comfortable',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'beginner',
    category: 'daily-life',
  },
  {
    title: 'delicious',
    text: 'delicious',
    type: 'word',
    tags: ['adjective', 'food'],
    difficulty: 'beginner',
    category: 'food',
  },
  {
    title: 'journey',
    text: 'journey',
    type: 'word',
    tags: ['noun', 'travel'],
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'adventure',
    text: 'adventure',
    type: 'word',
    tags: ['noun', 'travel'],
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'curious',
    text: 'curious',
    type: 'word',
    tags: ['adjective', 'emotions'],
    difficulty: 'beginner',
    category: 'emotions',
  },
  {
    title: 'generous',
    text: 'generous',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'beginner',
    category: 'emotions',
  },
  {
    title: 'breakfast',
    text: 'breakfast',
    type: 'word',
    tags: ['noun', 'food'],
    difficulty: 'beginner',
    category: 'food',
  },
  {
    title: 'weather',
    text: 'weather',
    type: 'word',
    tags: ['noun', 'nature'],
    difficulty: 'beginner',
    category: 'nature',
  },
  { title: 'family', text: 'family', type: 'word', tags: ['noun'], difficulty: 'beginner', category: 'daily-life' },
  { title: 'friend', text: 'friend', type: 'word', tags: ['noun'], difficulty: 'beginner', category: 'daily-life' },
  {
    title: 'experience',
    text: 'experience',
    type: 'word',
    tags: ['noun', 'education'],
    difficulty: 'intermediate',
    category: 'education',
  },
  {
    title: 'knowledge',
    text: 'knowledge',
    type: 'word',
    tags: ['noun', 'education'],
    difficulty: 'intermediate',
    category: 'education',
  },
  {
    title: 'environment',
    text: 'environment',
    type: 'word',
    tags: ['noun', 'nature'],
    difficulty: 'intermediate',
    category: 'nature',
  },
  {
    title: 'technology',
    text: 'technology',
    type: 'word',
    tags: ['noun', 'technology'],
    difficulty: 'intermediate',
    category: 'technology',
  },
  {
    title: 'communication',
    text: 'communication',
    type: 'word',
    tags: ['noun', 'social'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'opportunity',
    text: 'opportunity',
    type: 'word',
    tags: ['noun', 'business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'analyze',
    text: 'analyze',
    type: 'word',
    tags: ['verb', 'academic'],
    difficulty: 'intermediate',
    category: 'academic',
  },
  {
    title: 'significant',
    text: 'significant',
    type: 'word',
    tags: ['adjective', 'academic'],
    difficulty: 'intermediate',
    category: 'academic',
  },
  {
    title: 'hypothesis',
    text: 'hypothesis',
    type: 'word',
    tags: ['noun', 'science'],
    difficulty: 'intermediate',
    category: 'science',
  },
  {
    title: 'negotiate',
    text: 'negotiate',
    type: 'word',
    tags: ['verb', 'business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'responsibility',
    text: 'responsibility',
    type: 'word',
    tags: ['noun', 'character'],
    difficulty: 'advanced',
    category: 'formal',
  },
  {
    title: 'extraordinary',
    text: 'extraordinary',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'advanced',
    category: 'formal',
  },
  {
    title: 'sophisticated',
    text: 'sophisticated',
    type: 'word',
    tags: ['adjective'],
    difficulty: 'advanced',
    category: 'formal',
  },
  {
    title: 'ubiquitous',
    text: 'ubiquitous',
    type: 'word',
    tags: ['adjective', 'academic'],
    difficulty: 'advanced',
    category: 'academic',
  },
  {
    title: 'paradigm',
    text: 'paradigm',
    type: 'word',
    tags: ['noun', 'academic'],
    difficulty: 'advanced',
    category: 'academic',
  },
  {
    title: 'ephemeral',
    text: 'ephemeral',
    type: 'word',
    tags: ['adjective', 'literature'],
    difficulty: 'advanced',
    category: 'literature',
  },
  {
    title: 'serendipity',
    text: 'serendipity',
    type: 'word',
    tags: ['noun'],
    difficulty: 'advanced',
    category: 'literature',
  },
  {
    title: 'resilience',
    text: 'resilience',
    type: 'word',
    tags: ['noun', 'character'],
    difficulty: 'advanced',
    category: 'formal',
  },
];

const builtinPhrases: SeedItem[] = [
  {
    title: 'Good morning',
    text: 'Good morning',
    type: 'phrase',
    tags: ['greeting'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'How are you',
    text: 'How are you doing today',
    type: 'phrase',
    tags: ['greeting'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Nice to meet you',
    text: 'Nice to meet you',
    type: 'phrase',
    tags: ['greeting'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Thank you very much',
    text: 'Thank you very much',
    type: 'phrase',
    tags: ['polite'],
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'See you later',
    text: 'See you later',
    type: 'phrase',
    tags: ['farewell'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Excuse me',
    text: 'Excuse me, could I ask you something?',
    type: 'phrase',
    tags: ['polite'],
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'Could you please help me',
    text: 'Could you please help me with this?',
    type: 'phrase',
    tags: ['polite'],
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I would like to order',
    text: 'I would like to order a coffee, please',
    type: 'phrase',
    tags: ['daily', 'food'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'What do you think',
    text: 'What do you think about this idea?',
    type: 'phrase',
    tags: ['daily'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Let me know',
    text: 'Let me know if you need anything',
    type: 'phrase',
    tags: ['polite'],
    difficulty: 'beginner',
    category: 'polite',
  },
  {
    title: 'I hope this email finds you well',
    text: 'I hope this email finds you well',
    type: 'phrase',
    tags: ['email', 'polite'],
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'Looking forward to hearing from you',
    text: 'Looking forward to hearing from you',
    type: 'phrase',
    tags: ['email', 'polite'],
    difficulty: 'beginner',
    category: 'email',
  },
  {
    title: 'Break a leg',
    text: 'Break a leg',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Piece of cake',
    text: 'It is a piece of cake',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Hit the nail on the head',
    text: 'You hit the nail on the head',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Under the weather',
    text: 'I am feeling under the weather',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'intermediate',
    category: 'idiom',
  },
  {
    title: 'Think outside the box',
    text: 'We need to think outside the box to solve this',
    type: 'phrase',
    tags: ['idiom', 'business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'On the same page',
    text: 'Let us make sure we are on the same page',
    type: 'phrase',
    tags: ['idiom', 'business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'The elephant in the room',
    text: 'Nobody wants to talk about the elephant in the room',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'A double-edged sword',
    text: 'Social media is a double-edged sword for modern society',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Cut to the chase',
    text: 'Let me cut to the chase and tell you what happened',
    type: 'phrase',
    tags: ['idiom'],
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'Go the extra mile',
    text: 'She always goes the extra mile for her clients',
    type: 'phrase',
    tags: ['idiom', 'business'],
    difficulty: 'advanced',
    category: 'idiom',
  },
  {
    title: 'How much does this cost',
    text: 'How much does this cost?',
    type: 'phrase',
    tags: ['travel', 'daily'],
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I would like to check in please',
    text: 'I would like to check in, please',
    type: 'phrase',
    tags: ['travel', 'polite'],
    difficulty: 'beginner',
    category: 'travel',
  },
  {
    title: 'I have a reservation',
    text: 'I have a reservation under the name Johnson',
    type: 'phrase',
    tags: ['travel'],
    difficulty: 'beginner',
    category: 'travel',
  },
];

const builtinSentences: SeedItem[] = [
  {
    title: 'Learning English',
    text: 'Learning English opens doors to new opportunities around the world.',
    type: 'sentence',
    tags: ['motivation'],
    difficulty: 'beginner',
    category: 'motivation',
  },
  {
    title: 'Practice makes perfect',
    text: 'Practice makes perfect, so keep trying every day.',
    type: 'sentence',
    tags: ['motivation'],
    difficulty: 'beginner',
    category: 'motivation',
  },
  {
    title: 'Morning walk',
    text: 'I like to take a walk in the park every morning.',
    type: 'sentence',
    tags: ['daily'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Sunny weather',
    text: 'The weather is sunny and warm today, perfect for a picnic.',
    type: 'sentence',
    tags: ['daily', 'nature'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Favorite hobby',
    text: 'My favorite hobby is reading books before bedtime.',
    type: 'sentence',
    tags: ['daily'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Cooking dinner',
    text: 'She enjoys cooking dinner for her family on weekends.',
    type: 'sentence',
    tags: ['daily', 'food'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Family trip',
    text: 'We are planning a family trip to the mountains next summer.',
    type: 'sentence',
    tags: ['travel'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'New school',
    text: 'Starting at a new school can be both exciting and scary.',
    type: 'sentence',
    tags: ['education'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Shopping list',
    text: 'Please add milk and bread to the shopping list.',
    type: 'sentence',
    tags: ['daily'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Reading books',
    text: 'Reading books is one of the best ways to improve your vocabulary.',
    type: 'sentence',
    tags: ['education'],
    difficulty: 'intermediate',
    category: 'education',
  },
  {
    title: 'Communication skills',
    text: 'Good communication skills are essential for success in both personal and professional life.',
    type: 'sentence',
    tags: ['business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Technology and education',
    text: 'Technology has transformed the way we learn and communicate with each other.',
    type: 'sentence',
    tags: ['technology'],
    difficulty: 'intermediate',
    category: 'science',
  },
  {
    title: 'Climate change',
    text: 'Scientists around the world are working together to find solutions to climate change.',
    type: 'sentence',
    tags: ['science', 'nature'],
    difficulty: 'intermediate',
    category: 'science',
  },
  {
    title: 'Career growth',
    text: 'Continuous learning and adapting to new challenges are key factors in career growth.',
    type: 'sentence',
    tags: ['business'],
    difficulty: 'intermediate',
    category: 'business',
  },
  {
    title: 'Mark Twain on travel',
    text: 'Travel is fatal to prejudice, bigotry, and narrow-mindedness, and many of our people need it sorely on these accounts.',
    type: 'sentence',
    tags: ['literature', 'quote'],
    difficulty: 'advanced',
    category: 'literature',
  },
  {
    title: 'Einstein on imagination',
    text: 'Imagination is more important than knowledge, for knowledge is limited, whereas imagination embraces the entire world.',
    type: 'sentence',
    tags: ['science', 'quote'],
    difficulty: 'advanced',
    category: 'literature',
  },
  {
    title: 'Lincoln on preparation',
    text: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.',
    type: 'sentence',
    tags: ['motivation', 'quote'],
    difficulty: 'advanced',
    category: 'literature',
  },
  {
    title: 'Shakespeare on brevity',
    text: 'Brevity is the soul of wit.',
    type: 'sentence',
    tags: ['literature', 'quote'],
    difficulty: 'advanced',
    category: 'literature',
  },
];

const builtinArticles: SeedItem[] = [
  {
    title: 'The Joy of Learning',
    text: 'Learning a new language is like opening a window to a different world. Every word you learn brings you closer to understanding another culture. The journey may be challenging, but the rewards are immeasurable. Start with simple words and phrases, then gradually build your way up to more complex sentences and conversations.',
    type: 'article',
    tags: ['motivation', 'education'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'My Morning Routine',
    text: "Every morning, I wake up at seven o'clock. First, I brush my teeth and wash my face. Then I go to the kitchen to make breakfast. I usually have toast with butter and a glass of orange juice. After breakfast, I get dressed and check my bag for school. I like to leave the house early so I can walk slowly and enjoy the fresh air. On the way, I sometimes see my neighbors walking their dogs. When I arrive at school, I feel ready to start a new day of learning.",
    type: 'article',
    tags: ['daily', 'routine'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Seasons of the Year',
    text: 'There are four seasons in a year: spring, summer, fall, and winter. In spring, flowers begin to bloom and birds sing in the trees. The weather becomes warm and sunny. Summer is the hottest season. People go swimming and eat ice cream to stay cool. In fall, the leaves change color and fall from the trees. The air becomes crisp and cool. Winter is the coldest season. Snow covers the ground and children build snowmen. Each season is special and beautiful in its own way.',
    type: 'article',
    tags: ['nature', 'education'],
    difficulty: 'beginner',
    category: 'nature',
  },
  {
    title: 'A Visit to the Market',
    text: 'Last Saturday, I went to the farmers market with my mother. The market was full of fresh fruits and vegetables. We bought red apples, yellow bananas, and green lettuce. There was also a stand selling fresh bread that smelled wonderful. My mother picked some tomatoes and carrots for dinner. I chose a bunch of grapes as a snack. The market was busy and colorful. I love going to the market because everything is so fresh and the people are always friendly.',
    type: 'article',
    tags: ['daily', 'food'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'My Best Friend',
    text: 'My best friend is named Sarah. We met in school when we were both seven years old. She sat next to me in class and we started talking about our favorite books. Since then, we have been best friends. Sarah is kind, funny, and always ready to help. We like to ride our bikes together on weekends. Sometimes we go to the library to read or study. When I feel sad, Sarah always knows how to make me smile. I am very lucky to have such a wonderful friend.',
    type: 'article',
    tags: ['daily', 'friendship'],
    difficulty: 'beginner',
    category: 'daily',
  },
  {
    title: 'Digital Communication',
    text: 'In the modern world, digital communication has become an essential part of our daily lives. From emails to social media, we constantly use written English to express our thoughts and ideas. Improving your English writing skills can help you communicate more effectively in both personal and professional settings. The key is consistent practice and a willingness to learn from your mistakes.',
    type: 'article',
    tags: ['technology', 'communication'],
    difficulty: 'intermediate',
    category: 'technology',
  },
  {
    title: 'How the Internet Changed Communication',
    text: 'The internet has revolutionized the way people communicate with each other. Before the internet, people relied on letters, telephone calls, and face-to-face meetings to stay in touch. Today, we can send messages instantly to anyone in the world through email, social media, and messaging apps. Video calls allow us to see and talk to people thousands of miles away as if they were in the same room.',
    type: 'article',
    tags: ['technology', 'communication'],
    difficulty: 'intermediate',
    category: 'technology',
  },
  {
    title: 'Coffee Around the World',
    text: 'Coffee is one of the most popular beverages in the world, and different cultures have developed their own unique ways of preparing and enjoying it. In Italy, espresso is the standard, served in small cups and often consumed quickly while standing at a bar. Turkish coffee is prepared by boiling finely ground coffee beans with water and sugar in a special pot called a cezve. In Ethiopia, where coffee originated, the coffee ceremony is an important social ritual that can last several hours.',
    type: 'article',
    tags: ['culture', 'food'],
    difficulty: 'intermediate',
    category: 'culture',
  },
  {
    title: 'The Benefits of Reading',
    text: 'Reading is one of the most valuable habits a person can develop. Research has shown that regular reading improves vocabulary, enhances memory, and strengthens analytical thinking skills. When we read, our brains create new neural pathways and reinforce existing ones, which helps maintain cognitive function as we age. Reading fiction, in particular, has been linked to increased empathy, as it allows readers to experience the world through different perspectives.',
    type: 'article',
    tags: ['education', 'health'],
    difficulty: 'intermediate',
    category: 'education',
  },
  {
    title: 'The Art of Public Speaking',
    text: 'Public speaking is often cited as one of the most common fears, yet it remains one of the most valuable skills in professional life. Whether you are presenting to a small team or addressing a large audience, the ability to articulate your ideas clearly and confidently can set you apart. The foundation of great public speaking lies in thorough preparation, understanding your audience, and practicing your delivery until it feels natural.',
    type: 'article',
    tags: ['business', 'communication'],
    difficulty: 'advanced',
    category: 'business',
  },
  {
    title: 'The Scientific Method',
    text: 'The scientific method is the foundation of modern scientific inquiry and has been instrumental in advancing human knowledge for centuries. At its core, the scientific method is a systematic approach to understanding the natural world through observation, experimentation, and analysis. The process typically begins with an observation that raises a question. The scientist then formulates a hypothesis, which is a testable explanation for the observed phenomenon.',
    type: 'article',
    tags: ['science', 'education'],
    difficulty: 'advanced',
    category: 'science',
  },
  {
    title: 'The Philosophy of Happiness',
    text: "The pursuit of happiness has been a central concern of philosophers, psychologists, and ordinary people throughout human history. Ancient Greek philosophers offered diverse perspectives on what constitutes a good life. Aristotle argued that happiness, or eudaimonia, is achieved through the practice of virtue and the fulfillment of one's potential. The Stoics, on the other hand, believed that happiness comes from accepting what we cannot control and focusing on our own thoughts and actions.",
    type: 'article',
    tags: ['literature', 'philosophy'],
    difficulty: 'advanced',
    category: 'literature',
  },
];

let nextId = 1;
function makeId() {
  return `seed-${nextId++}`;
}

function toContent(item: SeedItem, now: number): Content {
  const wordCount = item.text.split(/\s+/).length;
  return {
    id: makeId(),
    title: item.title,
    type: item.type,
    content: item.text,
    text: item.text,
    language: 'en',
    difficulty: item.difficulty,
    tags: item.category ? [...item.tags, item.category] : item.tags,
    source: 'builtin',
    wordCount,
    isStarred: false,
    progress: 0,
    createdAt: now,
    updatedAt: now,
    fsrsCard: cardToData(createNewCard()),
  };
}

export function getSeedContents(): Content[] {
  const now = Date.now();
  nextId = 1;
  const all = [...builtinWords, ...builtinPhrases, ...builtinSentences, ...builtinArticles];
  return all.map((item) => toContent(item, now));
}

export async function hasBeenSeeded(): Promise<boolean> {
  const val = await AsyncStorage.getItem(SEED_KEY);
  return val === 'true';
}

export async function markSeeded(): Promise<void> {
  await AsyncStorage.setItem(SEED_KEY, 'true');
}
